// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: vaulticdb/v1/daemon.proto

package vaulticdbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VaulticDB_Health_FullMethodName                   = "/vaulticdb.v1.VaulticDB/Health"
	VaulticDB_Capabilities_FullMethodName             = "/vaulticdb.v1.VaulticDB/Capabilities"
	VaulticDB_WriterStatus_FullMethodName             = "/vaulticdb.v1.VaulticDB/WriterStatus"
	VaulticDB_DemoteWriter_FullMethodName             = "/vaulticdb.v1.VaulticDB/DemoteWriter"
	VaulticDB_PromoteWriter_FullMethodName            = "/vaulticdb.v1.VaulticDB/PromoteWriter"
	VaulticDB_GenerationStatus_FullMethodName         = "/vaulticdb.v1.VaulticDB/GenerationStatus"
	VaulticDB_QuarantineGeneration_FullMethodName     = "/vaulticdb.v1.VaulticDB/QuarantineGeneration"
	VaulticDB_ActivateGeneration_FullMethodName       = "/vaulticdb.v1.VaulticDB/ActivateGeneration"
	VaulticDB_VerifyGeneration_FullMethodName         = "/vaulticdb.v1.VaulticDB/VerifyGeneration"
	VaulticDB_RollbackGeneration_FullMethodName       = "/vaulticdb.v1.VaulticDB/RollbackGeneration"
	VaulticDB_RetireGeneration_FullMethodName         = "/vaulticdb.v1.VaulticDB/RetireGeneration"
	VaulticDB_Drain_FullMethodName                    = "/vaulticdb.v1.VaulticDB/Drain"
	VaulticDB_Shutdown_FullMethodName                 = "/vaulticdb.v1.VaulticDB/Shutdown"
	VaulticDB_Get_FullMethodName                      = "/vaulticdb.v1.VaulticDB/Get"
	VaulticDB_MultiGet_FullMethodName                 = "/vaulticdb.v1.VaulticDB/MultiGet"
	VaulticDB_Scan_FullMethodName                     = "/vaulticdb.v1.VaulticDB/Scan"
	VaulticDB_WriteBatch_FullMethodName               = "/vaulticdb.v1.VaulticDB/WriteBatch"
	VaulticDB_Begin_FullMethodName                    = "/vaulticdb.v1.VaulticDB/Begin"
	VaulticDB_Commit_FullMethodName                   = "/vaulticdb.v1.VaulticDB/Commit"
	VaulticDB_Rollback_FullMethodName                 = "/vaulticdb.v1.VaulticDB/Rollback"
	VaulticDB_GetMasterKey_FullMethodName             = "/vaulticdb.v1.VaulticDB/GetMasterKey"
	VaulticDB_StoreMasterKey_FullMethodName           = "/vaulticdb.v1.VaulticDB/StoreMasterKey"
	VaulticDB_KeyStatus_FullMethodName                = "/vaulticdb.v1.VaulticDB/KeyStatus"
	VaulticDB_AddLocalKeySlot_FullMethodName          = "/vaulticdb.v1.VaulticDB/AddLocalKeySlot"
	VaulticDB_AddCloudKeySlot_FullMethodName          = "/vaulticdb.v1.VaulticDB/AddCloudKeySlot"
	VaulticDB_RemoveKeySlot_FullMethodName            = "/vaulticdb.v1.VaulticDB/RemoveKeySlot"
	VaulticDB_RotateLocalKeySlot_FullMethodName       = "/vaulticdb.v1.VaulticDB/RotateLocalKeySlot"
	VaulticDB_RotateDek_FullMethodName                = "/vaulticdb.v1.VaulticDB/RotateDek"
	VaulticDB_RewriteDek_FullMethodName               = "/vaulticdb.v1.VaulticDB/RewriteDek"
	VaulticDB_EscrowMasterKey_FullMethodName          = "/vaulticdb.v1.VaulticDB/EscrowMasterKey"
	VaulticDB_RecoverEscrow_FullMethodName            = "/vaulticdb.v1.VaulticDB/RecoverEscrow"
	VaulticDB_ExportKeyEnvelope_FullMethodName        = "/vaulticdb.v1.VaulticDB/ExportKeyEnvelope"
	VaulticDB_CheckEncryption_FullMethodName          = "/vaulticdb.v1.VaulticDB/CheckEncryption"
	VaulticDB_PrepareCapsuleMigration_FullMethodName  = "/vaulticdb.v1.VaulticDB/PrepareCapsuleMigration"
	VaulticDB_FinalizeCapsuleMigration_FullMethodName = "/vaulticdb.v1.VaulticDB/FinalizeCapsuleMigration"
	VaulticDB_PublishCapsuleMutation_FullMethodName   = "/vaulticdb.v1.VaulticDB/PublishCapsuleMutation"
)

// VaulticDBClient is the client API for VaulticDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VaulticDBClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	WriterStatus(ctx context.Context, in *WriterStatusRequest, opts ...grpc.CallOption) (*WriterStatusResponse, error)
	DemoteWriter(ctx context.Context, in *DemoteWriterRequest, opts ...grpc.CallOption) (*WriterStatusResponse, error)
	PromoteWriter(ctx context.Context, in *PromoteWriterRequest, opts ...grpc.CallOption) (*WriterStatusResponse, error)
	GenerationStatus(ctx context.Context, in *GenerationStatusRequest, opts ...grpc.CallOption) (*GenerationStatusResponse, error)
	QuarantineGeneration(ctx context.Context, in *QuarantineGenerationRequest, opts ...grpc.CallOption) (*GenerationStatusResponse, error)
	ActivateGeneration(ctx context.Context, in *ActivateGenerationRequest, opts ...grpc.CallOption) (*GenerationStatusResponse, error)
	VerifyGeneration(ctx context.Context, in *VerifyGenerationRequest, opts ...grpc.CallOption) (*GenerationStatusResponse, error)
	RollbackGeneration(ctx context.Context, in *RollbackGenerationRequest, opts ...grpc.CallOption) (*GenerationStatusResponse, error)
	RetireGeneration(ctx context.Context, in *RetireGenerationRequest, opts ...grpc.CallOption) (*GenerationStatusResponse, error)
	Drain(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	MultiGet(ctx context.Context, in *MultiGetRequest, opts ...grpc.CallOption) (*MultiGetResponse, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	WriteBatch(ctx context.Context, in *WriteBatchRequest, opts ...grpc.CallOption) (*WriteBatchResponse, error)
	Begin(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BeginResponse, error)
	Commit(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	Rollback(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*Empty, error)
	GetMasterKey(ctx context.Context, in *MasterKeyRequest, opts ...grpc.CallOption) (*MasterKeyResponse, error)
	StoreMasterKey(ctx context.Context, in *StoreMasterKeyRequest, opts ...grpc.CallOption) (*Empty, error)
	KeyStatus(ctx context.Context, in *KeyStatusRequest, opts ...grpc.CallOption) (*KeyStatusResponse, error)
	AddLocalKeySlot(ctx context.Context, in *AddLocalKeySlotRequest, opts ...grpc.CallOption) (*KeyStatusResponse, error)
	AddCloudKeySlot(ctx context.Context, in *AddCloudKeySlotRequest, opts ...grpc.CallOption) (*KeyStatusResponse, error)
	RemoveKeySlot(ctx context.Context, in *RemoveKeySlotRequest, opts ...grpc.CallOption) (*KeyStatusResponse, error)
	RotateLocalKeySlot(ctx context.Context, in *RotateLocalKeySlotRequest, opts ...grpc.CallOption) (*KeyStatusResponse, error)
	RotateDek(ctx context.Context, in *RotateDekRequest, opts ...grpc.CallOption) (*KeyStatusResponse, error)
	RewriteDek(ctx context.Context, in *RewriteDekRequest, opts ...grpc.CallOption) (*RewriteDekResponse, error)
	EscrowMasterKey(ctx context.Context, in *EscrowMasterKeyRequest, opts ...grpc.CallOption) (*EscrowMasterKeyResponse, error)
	RecoverEscrow(ctx context.Context, in *RecoverEscrowRequest, opts ...grpc.CallOption) (*MasterKeyResponse, error)
	ExportKeyEnvelope(ctx context.Context, in *KeyStatusRequest, opts ...grpc.CallOption) (*ExportKeyEnvelopeResponse, error)
	CheckEncryption(ctx context.Context, in *KeyStatusRequest, opts ...grpc.CallOption) (*EncryptionAuditResponse, error)
	PrepareCapsuleMigration(ctx context.Context, in *PrepareCapsuleMigrationRequest, opts ...grpc.CallOption) (*PrepareCapsuleMigrationResponse, error)
	FinalizeCapsuleMigration(ctx context.Context, in *FinalizeCapsuleMigrationRequest, opts ...grpc.CallOption) (*Empty, error)
	PublishCapsuleMutation(ctx context.Context, in *PublishCapsuleMutationRequest, opts ...grpc.CallOption) (*PublishCapsuleMutationResponse, error)
}

type vaulticDBClient struct {
	cc grpc.ClientConnInterface
}

func NewVaulticDBClient(cc grpc.ClientConnInterface) VaulticDBClient {
	return &vaulticDBClient{cc}
}

func (c *vaulticDBClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, VaulticDB_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, VaulticDB_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) WriterStatus(ctx context.Context, in *WriterStatusRequest, opts ...grpc.CallOption) (*WriterStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriterStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_WriterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) DemoteWriter(ctx context.Context, in *DemoteWriterRequest, opts ...grpc.CallOption) (*WriterStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriterStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_DemoteWriter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) PromoteWriter(ctx context.Context, in *PromoteWriterRequest, opts ...grpc.CallOption) (*WriterStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriterStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_PromoteWriter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) GenerationStatus(ctx context.Context, in *GenerationStatusRequest, opts ...grpc.CallOption) (*GenerationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerationStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_GenerationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) QuarantineGeneration(ctx context.Context, in *QuarantineGenerationRequest, opts ...grpc.CallOption) (*GenerationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerationStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_QuarantineGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) ActivateGeneration(ctx context.Context, in *ActivateGenerationRequest, opts ...grpc.CallOption) (*GenerationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerationStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_ActivateGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) VerifyGeneration(ctx context.Context, in *VerifyGenerationRequest, opts ...grpc.CallOption) (*GenerationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerationStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_VerifyGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) RollbackGeneration(ctx context.Context, in *RollbackGenerationRequest, opts ...grpc.CallOption) (*GenerationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerationStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_RollbackGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) RetireGeneration(ctx context.Context, in *RetireGenerationRequest, opts ...grpc.CallOption) (*GenerationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerationStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_RetireGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) Drain(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VaulticDB_Drain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VaulticDB_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, VaulticDB_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) MultiGet(ctx context.Context, in *MultiGetRequest, opts ...grpc.CallOption) (*MultiGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultiGetResponse)
	err := c.cc.Invoke(ctx, VaulticDB_MultiGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, VaulticDB_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) WriteBatch(ctx context.Context, in *WriteBatchRequest, opts ...grpc.CallOption) (*WriteBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteBatchResponse)
	err := c.cc.Invoke(ctx, VaulticDB_WriteBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) Begin(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BeginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginResponse)
	err := c.cc.Invoke(ctx, VaulticDB_Begin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) Commit(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, VaulticDB_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) Rollback(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VaulticDB_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) GetMasterKey(ctx context.Context, in *MasterKeyRequest, opts ...grpc.CallOption) (*MasterKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MasterKeyResponse)
	err := c.cc.Invoke(ctx, VaulticDB_GetMasterKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) StoreMasterKey(ctx context.Context, in *StoreMasterKeyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VaulticDB_StoreMasterKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) KeyStatus(ctx context.Context, in *KeyStatusRequest, opts ...grpc.CallOption) (*KeyStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_KeyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) AddLocalKeySlot(ctx context.Context, in *AddLocalKeySlotRequest, opts ...grpc.CallOption) (*KeyStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_AddLocalKeySlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) AddCloudKeySlot(ctx context.Context, in *AddCloudKeySlotRequest, opts ...grpc.CallOption) (*KeyStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_AddCloudKeySlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) RemoveKeySlot(ctx context.Context, in *RemoveKeySlotRequest, opts ...grpc.CallOption) (*KeyStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_RemoveKeySlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) RotateLocalKeySlot(ctx context.Context, in *RotateLocalKeySlotRequest, opts ...grpc.CallOption) (*KeyStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_RotateLocalKeySlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) RotateDek(ctx context.Context, in *RotateDekRequest, opts ...grpc.CallOption) (*KeyStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyStatusResponse)
	err := c.cc.Invoke(ctx, VaulticDB_RotateDek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) RewriteDek(ctx context.Context, in *RewriteDekRequest, opts ...grpc.CallOption) (*RewriteDekResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RewriteDekResponse)
	err := c.cc.Invoke(ctx, VaulticDB_RewriteDek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) EscrowMasterKey(ctx context.Context, in *EscrowMasterKeyRequest, opts ...grpc.CallOption) (*EscrowMasterKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EscrowMasterKeyResponse)
	err := c.cc.Invoke(ctx, VaulticDB_EscrowMasterKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) RecoverEscrow(ctx context.Context, in *RecoverEscrowRequest, opts ...grpc.CallOption) (*MasterKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MasterKeyResponse)
	err := c.cc.Invoke(ctx, VaulticDB_RecoverEscrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) ExportKeyEnvelope(ctx context.Context, in *KeyStatusRequest, opts ...grpc.CallOption) (*ExportKeyEnvelopeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportKeyEnvelopeResponse)
	err := c.cc.Invoke(ctx, VaulticDB_ExportKeyEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) CheckEncryption(ctx context.Context, in *KeyStatusRequest, opts ...grpc.CallOption) (*EncryptionAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptionAuditResponse)
	err := c.cc.Invoke(ctx, VaulticDB_CheckEncryption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) PrepareCapsuleMigration(ctx context.Context, in *PrepareCapsuleMigrationRequest, opts ...grpc.CallOption) (*PrepareCapsuleMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareCapsuleMigrationResponse)
	err := c.cc.Invoke(ctx, VaulticDB_PrepareCapsuleMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) FinalizeCapsuleMigration(ctx context.Context, in *FinalizeCapsuleMigrationRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VaulticDB_FinalizeCapsuleMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDBClient) PublishCapsuleMutation(ctx context.Context, in *PublishCapsuleMutationRequest, opts ...grpc.CallOption) (*PublishCapsuleMutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishCapsuleMutationResponse)
	err := c.cc.Invoke(ctx, VaulticDB_PublishCapsuleMutation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VaulticDBServer is the server API for VaulticDB service.
// All implementations must embed UnimplementedVaulticDBServer
// for forward compatibility.
type VaulticDBServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	WriterStatus(context.Context, *WriterStatusRequest) (*WriterStatusResponse, error)
	DemoteWriter(context.Context, *DemoteWriterRequest) (*WriterStatusResponse, error)
	PromoteWriter(context.Context, *PromoteWriterRequest) (*WriterStatusResponse, error)
	GenerationStatus(context.Context, *GenerationStatusRequest) (*GenerationStatusResponse, error)
	QuarantineGeneration(context.Context, *QuarantineGenerationRequest) (*GenerationStatusResponse, error)
	ActivateGeneration(context.Context, *ActivateGenerationRequest) (*GenerationStatusResponse, error)
	VerifyGeneration(context.Context, *VerifyGenerationRequest) (*GenerationStatusResponse, error)
	RollbackGeneration(context.Context, *RollbackGenerationRequest) (*GenerationStatusResponse, error)
	RetireGeneration(context.Context, *RetireGenerationRequest) (*GenerationStatusResponse, error)
	Drain(context.Context, *Empty) (*Empty, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	MultiGet(context.Context, *MultiGetRequest) (*MultiGetResponse, error)
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	WriteBatch(context.Context, *WriteBatchRequest) (*WriteBatchResponse, error)
	Begin(context.Context, *Empty) (*BeginResponse, error)
	Commit(context.Context, *TransactionRequest) (*CommitResponse, error)
	Rollback(context.Context, *TransactionRequest) (*Empty, error)
	GetMasterKey(context.Context, *MasterKeyRequest) (*MasterKeyResponse, error)
	StoreMasterKey(context.Context, *StoreMasterKeyRequest) (*Empty, error)
	KeyStatus(context.Context, *KeyStatusRequest) (*KeyStatusResponse, error)
	AddLocalKeySlot(context.Context, *AddLocalKeySlotRequest) (*KeyStatusResponse, error)
	AddCloudKeySlot(context.Context, *AddCloudKeySlotRequest) (*KeyStatusResponse, error)
	RemoveKeySlot(context.Context, *RemoveKeySlotRequest) (*KeyStatusResponse, error)
	RotateLocalKeySlot(context.Context, *RotateLocalKeySlotRequest) (*KeyStatusResponse, error)
	RotateDek(context.Context, *RotateDekRequest) (*KeyStatusResponse, error)
	RewriteDek(context.Context, *RewriteDekRequest) (*RewriteDekResponse, error)
	EscrowMasterKey(context.Context, *EscrowMasterKeyRequest) (*EscrowMasterKeyResponse, error)
	RecoverEscrow(context.Context, *RecoverEscrowRequest) (*MasterKeyResponse, error)
	ExportKeyEnvelope(context.Context, *KeyStatusRequest) (*ExportKeyEnvelopeResponse, error)
	CheckEncryption(context.Context, *KeyStatusRequest) (*EncryptionAuditResponse, error)
	PrepareCapsuleMigration(context.Context, *PrepareCapsuleMigrationRequest) (*PrepareCapsuleMigrationResponse, error)
	FinalizeCapsuleMigration(context.Context, *FinalizeCapsuleMigrationRequest) (*Empty, error)
	PublishCapsuleMutation(context.Context, *PublishCapsuleMutationRequest) (*PublishCapsuleMutationResponse, error)
	mustEmbedUnimplementedVaulticDBServer()
}

// UnimplementedVaulticDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVaulticDBServer struct{}

func (UnimplementedVaulticDBServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedVaulticDBServer) Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedVaulticDBServer) WriterStatus(context.Context, *WriterStatusRequest) (*WriterStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriterStatus not implemented")
}
func (UnimplementedVaulticDBServer) DemoteWriter(context.Context, *DemoteWriterRequest) (*WriterStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DemoteWriter not implemented")
}
func (UnimplementedVaulticDBServer) PromoteWriter(context.Context, *PromoteWriterRequest) (*WriterStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromoteWriter not implemented")
}
func (UnimplementedVaulticDBServer) GenerationStatus(context.Context, *GenerationStatusRequest) (*GenerationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerationStatus not implemented")
}
func (UnimplementedVaulticDBServer) QuarantineGeneration(context.Context, *QuarantineGenerationRequest) (*GenerationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuarantineGeneration not implemented")
}
func (UnimplementedVaulticDBServer) ActivateGeneration(context.Context, *ActivateGenerationRequest) (*GenerationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateGeneration not implemented")
}
func (UnimplementedVaulticDBServer) VerifyGeneration(context.Context, *VerifyGenerationRequest) (*GenerationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyGeneration not implemented")
}
func (UnimplementedVaulticDBServer) RollbackGeneration(context.Context, *RollbackGenerationRequest) (*GenerationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackGeneration not implemented")
}
func (UnimplementedVaulticDBServer) RetireGeneration(context.Context, *RetireGenerationRequest) (*GenerationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetireGeneration not implemented")
}
func (UnimplementedVaulticDBServer) Drain(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Drain not implemented")
}
func (UnimplementedVaulticDBServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedVaulticDBServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedVaulticDBServer) MultiGet(context.Context, *MultiGetRequest) (*MultiGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiGet not implemented")
}
func (UnimplementedVaulticDBServer) Scan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedVaulticDBServer) WriteBatch(context.Context, *WriteBatchRequest) (*WriteBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteBatch not implemented")
}
func (UnimplementedVaulticDBServer) Begin(context.Context, *Empty) (*BeginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Begin not implemented")
}
func (UnimplementedVaulticDBServer) Commit(context.Context, *TransactionRequest) (*CommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedVaulticDBServer) Rollback(context.Context, *TransactionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedVaulticDBServer) GetMasterKey(context.Context, *MasterKeyRequest) (*MasterKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMasterKey not implemented")
}
func (UnimplementedVaulticDBServer) StoreMasterKey(context.Context, *StoreMasterKeyRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreMasterKey not implemented")
}
func (UnimplementedVaulticDBServer) KeyStatus(context.Context, *KeyStatusRequest) (*KeyStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeyStatus not implemented")
}
func (UnimplementedVaulticDBServer) AddLocalKeySlot(context.Context, *AddLocalKeySlotRequest) (*KeyStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLocalKeySlot not implemented")
}
func (UnimplementedVaulticDBServer) AddCloudKeySlot(context.Context, *AddCloudKeySlotRequest) (*KeyStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCloudKeySlot not implemented")
}
func (UnimplementedVaulticDBServer) RemoveKeySlot(context.Context, *RemoveKeySlotRequest) (*KeyStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveKeySlot not implemented")
}
func (UnimplementedVaulticDBServer) RotateLocalKeySlot(context.Context, *RotateLocalKeySlotRequest) (*KeyStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateLocalKeySlot not implemented")
}
func (UnimplementedVaulticDBServer) RotateDek(context.Context, *RotateDekRequest) (*KeyStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateDek not implemented")
}
func (UnimplementedVaulticDBServer) RewriteDek(context.Context, *RewriteDekRequest) (*RewriteDekResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RewriteDek not implemented")
}
func (UnimplementedVaulticDBServer) EscrowMasterKey(context.Context, *EscrowMasterKeyRequest) (*EscrowMasterKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EscrowMasterKey not implemented")
}
func (UnimplementedVaulticDBServer) RecoverEscrow(context.Context, *RecoverEscrowRequest) (*MasterKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverEscrow not implemented")
}
func (UnimplementedVaulticDBServer) ExportKeyEnvelope(context.Context, *KeyStatusRequest) (*ExportKeyEnvelopeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportKeyEnvelope not implemented")
}
func (UnimplementedVaulticDBServer) CheckEncryption(context.Context, *KeyStatusRequest) (*EncryptionAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckEncryption not implemented")
}
func (UnimplementedVaulticDBServer) PrepareCapsuleMigration(context.Context, *PrepareCapsuleMigrationRequest) (*PrepareCapsuleMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareCapsuleMigration not implemented")
}
func (UnimplementedVaulticDBServer) FinalizeCapsuleMigration(context.Context, *FinalizeCapsuleMigrationRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeCapsuleMigration not implemented")
}
func (UnimplementedVaulticDBServer) PublishCapsuleMutation(context.Context, *PublishCapsuleMutationRequest) (*PublishCapsuleMutationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishCapsuleMutation not implemented")
}
func (UnimplementedVaulticDBServer) mustEmbedUnimplementedVaulticDBServer() {}
func (UnimplementedVaulticDBServer) testEmbeddedByValue()                   {}

// UnsafeVaulticDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VaulticDBServer will
// result in compilation errors.
type UnsafeVaulticDBServer interface {
	mustEmbedUnimplementedVaulticDBServer()
}

func RegisterVaulticDBServer(s grpc.ServiceRegistrar, srv VaulticDBServer) {
	// If the following call pancis, it indicates UnimplementedVaulticDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VaulticDB_ServiceDesc, srv)
}

func _VaulticDB_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_WriterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).WriterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_WriterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).WriterStatus(ctx, req.(*WriterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_DemoteWriter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoteWriterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).DemoteWriter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_DemoteWriter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).DemoteWriter(ctx, req.(*DemoteWriterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_PromoteWriter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteWriterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).PromoteWriter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_PromoteWriter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).PromoteWriter(ctx, req.(*PromoteWriterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_GenerationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).GenerationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_GenerationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).GenerationStatus(ctx, req.(*GenerationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_QuarantineGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuarantineGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).QuarantineGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_QuarantineGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).QuarantineGeneration(ctx, req.(*QuarantineGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_ActivateGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).ActivateGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_ActivateGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).ActivateGeneration(ctx, req.(*ActivateGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_VerifyGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).VerifyGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_VerifyGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).VerifyGeneration(ctx, req.(*VerifyGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_RollbackGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).RollbackGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_RollbackGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).RollbackGeneration(ctx, req.(*RollbackGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_RetireGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetireGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).RetireGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_RetireGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).RetireGeneration(ctx, req.(*RetireGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_Drain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).Drain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_Drain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).Drain(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_MultiGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).MultiGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_MultiGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).MultiGet(ctx, req.(*MultiGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_WriteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).WriteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_WriteBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).WriteBatch(ctx, req.(*WriteBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_Begin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).Begin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_Begin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).Begin(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).Commit(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).Rollback(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_GetMasterKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MasterKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).GetMasterKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_GetMasterKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).GetMasterKey(ctx, req.(*MasterKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_StoreMasterKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreMasterKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).StoreMasterKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_StoreMasterKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).StoreMasterKey(ctx, req.(*StoreMasterKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_KeyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).KeyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_KeyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).KeyStatus(ctx, req.(*KeyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_AddLocalKeySlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLocalKeySlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).AddLocalKeySlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_AddLocalKeySlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).AddLocalKeySlot(ctx, req.(*AddLocalKeySlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_AddCloudKeySlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCloudKeySlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).AddCloudKeySlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_AddCloudKeySlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).AddCloudKeySlot(ctx, req.(*AddCloudKeySlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_RemoveKeySlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveKeySlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).RemoveKeySlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_RemoveKeySlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).RemoveKeySlot(ctx, req.(*RemoveKeySlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_RotateLocalKeySlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateLocalKeySlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).RotateLocalKeySlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_RotateLocalKeySlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).RotateLocalKeySlot(ctx, req.(*RotateLocalKeySlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_RotateDek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateDekRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).RotateDek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_RotateDek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).RotateDek(ctx, req.(*RotateDekRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_RewriteDek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RewriteDekRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).RewriteDek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_RewriteDek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).RewriteDek(ctx, req.(*RewriteDekRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_EscrowMasterKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EscrowMasterKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).EscrowMasterKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_EscrowMasterKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).EscrowMasterKey(ctx, req.(*EscrowMasterKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_RecoverEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).RecoverEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_RecoverEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).RecoverEscrow(ctx, req.(*RecoverEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_ExportKeyEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).ExportKeyEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_ExportKeyEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).ExportKeyEnvelope(ctx, req.(*KeyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_CheckEncryption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).CheckEncryption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_CheckEncryption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).CheckEncryption(ctx, req.(*KeyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_PrepareCapsuleMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareCapsuleMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).PrepareCapsuleMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_PrepareCapsuleMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).PrepareCapsuleMigration(ctx, req.(*PrepareCapsuleMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_FinalizeCapsuleMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeCapsuleMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).FinalizeCapsuleMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_FinalizeCapsuleMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).FinalizeCapsuleMigration(ctx, req.(*FinalizeCapsuleMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDB_PublishCapsuleMutation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishCapsuleMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDBServer).PublishCapsuleMutation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDB_PublishCapsuleMutation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDBServer).PublishCapsuleMutation(ctx, req.(*PublishCapsuleMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VaulticDB_ServiceDesc is the grpc.ServiceDesc for VaulticDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VaulticDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vaulticdb.v1.VaulticDB",
	HandlerType: (*VaulticDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _VaulticDB_Health_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _VaulticDB_Capabilities_Handler,
		},
		{
			MethodName: "WriterStatus",
			Handler:    _VaulticDB_WriterStatus_Handler,
		},
		{
			MethodName: "DemoteWriter",
			Handler:    _VaulticDB_DemoteWriter_Handler,
		},
		{
			MethodName: "PromoteWriter",
			Handler:    _VaulticDB_PromoteWriter_Handler,
		},
		{
			MethodName: "GenerationStatus",
			Handler:    _VaulticDB_GenerationStatus_Handler,
		},
		{
			MethodName: "QuarantineGeneration",
			Handler:    _VaulticDB_QuarantineGeneration_Handler,
		},
		{
			MethodName: "ActivateGeneration",
			Handler:    _VaulticDB_ActivateGeneration_Handler,
		},
		{
			MethodName: "VerifyGeneration",
			Handler:    _VaulticDB_VerifyGeneration_Handler,
		},
		{
			MethodName: "RollbackGeneration",
			Handler:    _VaulticDB_RollbackGeneration_Handler,
		},
		{
			MethodName: "RetireGeneration",
			Handler:    _VaulticDB_RetireGeneration_Handler,
		},
		{
			MethodName: "Drain",
			Handler:    _VaulticDB_Drain_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _VaulticDB_Shutdown_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _VaulticDB_Get_Handler,
		},
		{
			MethodName: "MultiGet",
			Handler:    _VaulticDB_MultiGet_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _VaulticDB_Scan_Handler,
		},
		{
			MethodName: "WriteBatch",
			Handler:    _VaulticDB_WriteBatch_Handler,
		},
		{
			MethodName: "Begin",
			Handler:    _VaulticDB_Begin_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _VaulticDB_Commit_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _VaulticDB_Rollback_Handler,
		},
		{
			MethodName: "GetMasterKey",
			Handler:    _VaulticDB_GetMasterKey_Handler,
		},
		{
			MethodName: "StoreMasterKey",
			Handler:    _VaulticDB_StoreMasterKey_Handler,
		},
		{
			MethodName: "KeyStatus",
			Handler:    _VaulticDB_KeyStatus_Handler,
		},
		{
			MethodName: "AddLocalKeySlot",
			Handler:    _VaulticDB_AddLocalKeySlot_Handler,
		},
		{
			MethodName: "AddCloudKeySlot",
			Handler:    _VaulticDB_AddCloudKeySlot_Handler,
		},
		{
			MethodName: "RemoveKeySlot",
			Handler:    _VaulticDB_RemoveKeySlot_Handler,
		},
		{
			MethodName: "RotateLocalKeySlot",
			Handler:    _VaulticDB_RotateLocalKeySlot_Handler,
		},
		{
			MethodName: "RotateDek",
			Handler:    _VaulticDB_RotateDek_Handler,
		},
		{
			MethodName: "RewriteDek",
			Handler:    _VaulticDB_RewriteDek_Handler,
		},
		{
			MethodName: "EscrowMasterKey",
			Handler:    _VaulticDB_EscrowMasterKey_Handler,
		},
		{
			MethodName: "RecoverEscrow",
			Handler:    _VaulticDB_RecoverEscrow_Handler,
		},
		{
			MethodName: "ExportKeyEnvelope",
			Handler:    _VaulticDB_ExportKeyEnvelope_Handler,
		},
		{
			MethodName: "CheckEncryption",
			Handler:    _VaulticDB_CheckEncryption_Handler,
		},
		{
			MethodName: "PrepareCapsuleMigration",
			Handler:    _VaulticDB_PrepareCapsuleMigration_Handler,
		},
		{
			MethodName: "FinalizeCapsuleMigration",
			Handler:    _VaulticDB_FinalizeCapsuleMigration_Handler,
		},
		{
			MethodName: "PublishCapsuleMutation",
			Handler:    _VaulticDB_PublishCapsuleMutation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vaulticdb/v1/daemon.proto",
}
