// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.0
// source: vaulticdb/v1/daemon.proto

package vaulticdbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DeadlineUnixMs int64                  `protobuf:"varint,2,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_vaulticdb_v1_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *RequestContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestContext) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_vaulticdb_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *Empty) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_vaulticdb_v1_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type BatchLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxItems      uint32                 `protobuf:"varint,1,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	MaxBytes      uint32                 `protobuf:"varint,2,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLimits) Reset() {
	*x = BatchLimits{}
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLimits) ProtoMessage() {}

func (x *BatchLimits) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLimits.ProtoReflect.Descriptor instead.
func (*BatchLimits) Descriptor() ([]byte, []int) {
	return file_vaulticdb_v1_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *BatchLimits) GetMaxItems() uint32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *BatchLimits) GetMaxBytes() uint32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_vaulticdb_v1_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type WriteBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Puts          []*KeyValue            `protobuf:"bytes,2,rep,name=puts,proto3" json:"puts,omitempty"`
	Deletes       [][]byte               `protobuf:"bytes,3,rep,name=deletes,proto3" json:"deletes,omitempty"`
	AwaitDurable  bool                   `protobuf:"varint,4,opt,name=await_durable,json=awaitDurable,proto3" json:"await_durable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchRequest) Reset() {
	*x = WriteBatchRequest{}
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBatchRequest) ProtoMessage() {}

func (x *WriteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBatchRequest.ProtoReflect.Descriptor instead.
func (*WriteBatchRequest) Descriptor() ([]byte, []int) {
	return file_vaulticdb_v1_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *WriteBatchRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *WriteBatchRequest) GetPuts() []*KeyValue {
	if x != nil {
		return x.Puts
	}
	return nil
}

func (x *WriteBatchRequest) GetDeletes() [][]byte {
	if x != nil {
		return x.Deletes
	}
	return nil
}

func (x *WriteBatchRequest) GetAwaitDurable() bool {
	if x != nil {
		return x.AwaitDurable
	}
	return false
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Prefix        []byte                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_vaulticdb_v1_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *ScanRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ScanRequest) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *ScanRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*KeyValue            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_vaulticdb_v1_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *ScanResponse) GetEntries() []*KeyValue {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ScanResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_vaulticdb_v1_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *TransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepositoryId  string                 `protobuf:"bytes,1,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	Context       *RequestContext        `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_vaulticdb_v1_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *HealthRequest) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

func (x *HealthRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DaemonId        string                 `protobuf:"bytes,1,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SchemaVersion   string                 `protobuf:"bytes,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RepositoryId    string                 `protobuf:"bytes,4,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	SlateDbRevision string                 `protobuf:"bytes,5,opt,name=slate_db_revision,json=slateDbRevision,proto3" json:"slate_db_revision,omitempty"`
	Ready           bool                   `protobuf:"varint,6,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_vaulticdb_v1_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *HealthResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HealthResponse) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *HealthResponse) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

func (x *HealthResponse) GetSlateDbRevision() string {
	if x != nil {
		return x.SlateDbRevision
	}
	return ""
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepositoryId  string                 `protobuf:"bytes,1,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	Context       *RequestContext        `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_vaulticdb_v1_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *CapabilitiesRequest) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

func (x *CapabilitiesRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type CapabilitiesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DaemonId        string                 `protobuf:"bytes,1,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SchemaVersion   string                 `protobuf:"bytes,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RepositoryId    string                 `protobuf:"bytes,4,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	UnixSocket      bool                   `protobuf:"varint,5,opt,name=unix_socket,json=unixSocket,proto3" json:"unix_socket,omitempty"`
	TcpEnabled      bool                   `protobuf:"varint,6,opt,name=tcp_enabled,json=tcpEnabled,proto3" json:"tcp_enabled,omitempty"`
	MaxBatchItems   uint32                 `protobuf:"varint,7,opt,name=max_batch_items,json=maxBatchItems,proto3" json:"max_batch_items,omitempty"`
	MaxMessageBytes uint32                 `protobuf:"varint,8,opt,name=max_message_bytes,json=maxMessageBytes,proto3" json:"max_message_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticdb_v1_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_vaulticdb_v1_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *CapabilitiesResponse) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *CapabilitiesResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

func (x *CapabilitiesResponse) GetUnixSocket() bool {
	if x != nil {
		return x.UnixSocket
	}
	return false
}

func (x *CapabilitiesResponse) GetTcpEnabled() bool {
	if x != nil {
		return x.TcpEnabled
	}
	return false
}

func (x *CapabilitiesResponse) GetMaxBatchItems() uint32 {
	if x != nil {
		return x.MaxBatchItems
	}
	return 0
}

func (x *CapabilitiesResponse) GetMaxMessageBytes() uint32 {
	if x != nil {
		return x.MaxMessageBytes
	}
	return 0
}

var File_vaulticdb_v1_daemon_proto protoreflect.FileDescriptor

const file_vaulticdb_v1_daemon_proto_rawDesc = "" +
	"\n" +
	"\x19vaulticdb/v1/daemon.proto\x12\fvaulticdb.v1\"Y\n" +
	"\x0eRequestContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12(\n" +
	"\x10deadline_unix_ms\x18\x02 \x01(\x03R\x0edeadlineUnixMs\"?\n" +
	"\x05Empty\x126\n" +
	"\acontext\x18\x01 \x01(\v2\x1c.vaulticdb.v1.RequestContextR\acontext\"Y\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"G\n" +
	"\vBatchLimits\x12\x1b\n" +
	"\tmax_items\x18\x01 \x01(\rR\bmaxItems\x12\x1b\n" +
	"\tmax_bytes\x18\x02 \x01(\rR\bmaxBytes\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xb6\x01\n" +
	"\x11WriteBatchRequest\x126\n" +
	"\acontext\x18\x01 \x01(\v2\x1c.vaulticdb.v1.RequestContextR\acontext\x12*\n" +
	"\x04puts\x18\x02 \x03(\v2\x16.vaulticdb.v1.KeyValueR\x04puts\x12\x18\n" +
	"\adeletes\x18\x03 \x03(\fR\adeletes\x12#\n" +
	"\rawait_durable\x18\x04 \x01(\bR\fawaitDurable\"z\n" +
	"\vScanRequest\x126\n" +
	"\acontext\x18\x01 \x01(\v2\x1c.vaulticdb.v1.RequestContextR\acontext\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\fR\x06prefix\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"T\n" +
	"\fScanResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.vaulticdb.v1.KeyValueR\aentries\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\"s\n" +
	"\x12TransactionRequest\x126\n" +
	"\acontext\x18\x01 \x01(\v2\x1c.vaulticdb.v1.RequestContextR\acontext\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"l\n" +
	"\rHealthRequest\x12#\n" +
	"\rrepository_id\x18\x01 \x01(\tR\frepositoryId\x126\n" +
	"\acontext\x18\x02 \x01(\v2\x1c.vaulticdb.v1.RequestContextR\acontext\"\xe6\x01\n" +
	"\x0eHealthResponse\x12\x1b\n" +
	"\tdaemon_id\x18\x01 \x01(\tR\bdaemonId\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\tR\rschemaVersion\x12#\n" +
	"\rrepository_id\x18\x04 \x01(\tR\frepositoryId\x12*\n" +
	"\x11slate_db_revision\x18\x05 \x01(\tR\x0fslateDbRevision\x12\x14\n" +
	"\x05ready\x18\x06 \x01(\bR\x05ready\"r\n" +
	"\x13CapabilitiesRequest\x12#\n" +
	"\rrepository_id\x18\x01 \x01(\tR\frepositoryId\x126\n" +
	"\acontext\x18\x02 \x01(\v2\x1c.vaulticdb.v1.RequestContextR\acontext\"\xc0\x02\n" +
	"\x14CapabilitiesResponse\x12\x1b\n" +
	"\tdaemon_id\x18\x01 \x01(\tR\bdaemonId\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\tR\rschemaVersion\x12#\n" +
	"\rrepository_id\x18\x04 \x01(\tR\frepositoryId\x12\x1f\n" +
	"\vunix_socket\x18\x05 \x01(\bR\n" +
	"unixSocket\x12\x1f\n" +
	"\vtcp_enabled\x18\x06 \x01(\bR\n" +
	"tcpEnabled\x12&\n" +
	"\x0fmax_batch_items\x18\a \x01(\rR\rmaxBatchItems\x12*\n" +
	"\x11max_message_bytes\x18\b \x01(\rR\x0fmaxMessageBytes2\x90\x02\n" +
	"\tVaulticDB\x12C\n" +
	"\x06Health\x12\x1b.vaulticdb.v1.HealthRequest\x1a\x1c.vaulticdb.v1.HealthResponse\x12U\n" +
	"\fCapabilities\x12!.vaulticdb.v1.CapabilitiesRequest\x1a\".vaulticdb.v1.CapabilitiesResponse\x121\n" +
	"\x05Drain\x12\x13.vaulticdb.v1.Empty\x1a\x13.vaulticdb.v1.Empty\x124\n" +
	"\bShutdown\x12\x13.vaulticdb.v1.Empty\x1a\x13.vaulticdb.v1.EmptyBLZJgithub.com/otuschhoff/vaultic/internal/index/proto/vaulticdbv1;vaulticdbv1b\x06proto3"

var (
	file_vaulticdb_v1_daemon_proto_rawDescOnce sync.Once
	file_vaulticdb_v1_daemon_proto_rawDescData []byte
)

func file_vaulticdb_v1_daemon_proto_rawDescGZIP() []byte {
	file_vaulticdb_v1_daemon_proto_rawDescOnce.Do(func() {
		file_vaulticdb_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vaulticdb_v1_daemon_proto_rawDesc), len(file_vaulticdb_v1_daemon_proto_rawDesc)))
	})
	return file_vaulticdb_v1_daemon_proto_rawDescData
}

var file_vaulticdb_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_vaulticdb_v1_daemon_proto_goTypes = []any{
	(*RequestContext)(nil),       // 0: vaulticdb.v1.RequestContext
	(*Empty)(nil),                // 1: vaulticdb.v1.Empty
	(*ErrorDetail)(nil),          // 2: vaulticdb.v1.ErrorDetail
	(*BatchLimits)(nil),          // 3: vaulticdb.v1.BatchLimits
	(*KeyValue)(nil),             // 4: vaulticdb.v1.KeyValue
	(*WriteBatchRequest)(nil),    // 5: vaulticdb.v1.WriteBatchRequest
	(*ScanRequest)(nil),          // 6: vaulticdb.v1.ScanRequest
	(*ScanResponse)(nil),         // 7: vaulticdb.v1.ScanResponse
	(*TransactionRequest)(nil),   // 8: vaulticdb.v1.TransactionRequest
	(*HealthRequest)(nil),        // 9: vaulticdb.v1.HealthRequest
	(*HealthResponse)(nil),       // 10: vaulticdb.v1.HealthResponse
	(*CapabilitiesRequest)(nil),  // 11: vaulticdb.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 12: vaulticdb.v1.CapabilitiesResponse
}
var file_vaulticdb_v1_daemon_proto_depIdxs = []int32{
	0,  // 0: vaulticdb.v1.Empty.context:type_name -> vaulticdb.v1.RequestContext
	0,  // 1: vaulticdb.v1.WriteBatchRequest.context:type_name -> vaulticdb.v1.RequestContext
	4,  // 2: vaulticdb.v1.WriteBatchRequest.puts:type_name -> vaulticdb.v1.KeyValue
	0,  // 3: vaulticdb.v1.ScanRequest.context:type_name -> vaulticdb.v1.RequestContext
	4,  // 4: vaulticdb.v1.ScanResponse.entries:type_name -> vaulticdb.v1.KeyValue
	0,  // 5: vaulticdb.v1.TransactionRequest.context:type_name -> vaulticdb.v1.RequestContext
	0,  // 6: vaulticdb.v1.HealthRequest.context:type_name -> vaulticdb.v1.RequestContext
	0,  // 7: vaulticdb.v1.CapabilitiesRequest.context:type_name -> vaulticdb.v1.RequestContext
	9,  // 8: vaulticdb.v1.VaulticDB.Health:input_type -> vaulticdb.v1.HealthRequest
	11, // 9: vaulticdb.v1.VaulticDB.Capabilities:input_type -> vaulticdb.v1.CapabilitiesRequest
	1,  // 10: vaulticdb.v1.VaulticDB.Drain:input_type -> vaulticdb.v1.Empty
	1,  // 11: vaulticdb.v1.VaulticDB.Shutdown:input_type -> vaulticdb.v1.Empty
	10, // 12: vaulticdb.v1.VaulticDB.Health:output_type -> vaulticdb.v1.HealthResponse
	12, // 13: vaulticdb.v1.VaulticDB.Capabilities:output_type -> vaulticdb.v1.CapabilitiesResponse
	1,  // 14: vaulticdb.v1.VaulticDB.Drain:output_type -> vaulticdb.v1.Empty
	1,  // 15: vaulticdb.v1.VaulticDB.Shutdown:output_type -> vaulticdb.v1.Empty
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_vaulticdb_v1_daemon_proto_init() }
func file_vaulticdb_v1_daemon_proto_init() {
	if File_vaulticdb_v1_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vaulticdb_v1_daemon_proto_rawDesc), len(file_vaulticdb_v1_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vaulticdb_v1_daemon_proto_goTypes,
		DependencyIndexes: file_vaulticdb_v1_daemon_proto_depIdxs,
		MessageInfos:      file_vaulticdb_v1_daemon_proto_msgTypes,
	}.Build()
	File_vaulticdb_v1_daemon_proto = out.File
	file_vaulticdb_v1_daemon_proto_goTypes = nil
	file_vaulticdb_v1_daemon_proto_depIdxs = nil
}
