package daemon

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"math"
	"slices"
	"sort"
	"time"

	"github.com/otuschhoff/vaultic/internal/index/schema"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

const revisionAllocationAttempts = 128

// SchemaStore applies the Vaultic schema's immutability and revision rules over
// the bounded daemon client.
type SchemaStore struct{ client *Client }

type LegacyPackImport struct {
	SourceIndex schema.ID
	PackID      schema.ID
	Record      schema.PackRecord
	Blobs       map[schema.ID]schema.BlobRecord
	BatchSize   uint32
	DebtKey     []byte
	Debt        *schema.CrawlDebtRecord
}

// PublishedPack contains the catalog and blob locations generated by a new
// backup pack. Unlike legacy imports it has no source JSON index.
type PublishedPack struct {
	PackID schema.ID
	Record schema.PackRecord
	Blobs  map[schema.ID]schema.BlobRecord
}

type SnapshotScope struct {
	SnapshotID   schema.ID
	RootKey      []byte
	OriginalJSON []byte
}

type ReconciledRevision struct {
	CurrentKey         []byte
	RevisionKey        []byte
	RevisionValue      []byte
	Revision           uint64
	ContentIDs         []schema.ID
	DebtKeys           [][]byte
	HasMultipleParents bool
	HardlinkParents    []schema.HardlinkParentRef
}

func NewSchemaStore(client *Client) *SchemaStore { return &SchemaStore{client: client} }

func (store *SchemaStore) Get(ctx context.Context, key []byte) ([]byte, bool, error) {
	if _, err := schema.ParseKey(key); err != nil {
		return nil, false, err
	}
	return store.client.Get(ctx, key, "")
}

// MultiGet reads a bounded set of schema records in request order.
func (store *SchemaStore) MultiGet(ctx context.Context, keys [][]byte) ([]KeyValue, []bool, error) {
	for _, key := range keys {
		if _, err := schema.ParseKey(key); err != nil {
			return nil, nil, err
		}
	}
	return store.client.MultiGet(ctx, keys, "")
}

// ScanPrefix reads one bounded schema page for an exact key prefix.
func (store *SchemaStore) ScanPrefix(ctx context.Context, prefix, afterKey []byte, pageSize uint32) ([]KeyValue, bool, error) {
	if pageSize > store.client.Limits().MaxPageItems {
		pageSize = store.client.Limits().MaxPageItems
	}
	return store.client.ScanPage(ctx, prefix, afterKey, pageSize, "")
}

// RecordCrawlDebtFailure leaves debt pending while atomically recording a
// failed reconciliation attempt for each existing debt key.
func (store *SchemaStore) RecordCrawlDebtFailure(ctx context.Context, keys [][]byte, errorClass string) error {
	if errorClass == "" {
		errorClass = "reconciliation-failed"
	}
	backoff := 100 * time.Microsecond
	for range revisionAllocationAttempts {
		err := store.recordCrawlDebtFailureOnce(ctx, keys, errorClass)
		if status.Code(err) != codes.Aborted {
			return err
		}
		timer := time.NewTimer(backoff)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
		}
		backoff = min(backoff*2, 25*time.Millisecond)
	}
	return fmt.Errorf("record crawl-debt failure: transaction conflict retry limit exceeded")
}

// ResolveCrawlDebt atomically marks existing debt records resolved without
// creating an otherwise identical metadata revision.
func (store *SchemaStore) ResolveCrawlDebt(ctx context.Context, keys [][]byte) error {
	backoff := 100 * time.Microsecond
	for range revisionAllocationAttempts {
		err := store.resolveCrawlDebtOnce(ctx, keys)
		if status.Code(err) != codes.Aborted {
			return err
		}
		timer := time.NewTimer(backoff)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
		}
		backoff = min(backoff*2, 25*time.Millisecond)
	}
	return fmt.Errorf("resolve crawl debt: transaction conflict retry limit exceeded")
}

func (store *SchemaStore) resolveCrawlDebtOnce(ctx context.Context, keys [][]byte) error {
	transaction, err := store.client.Begin(ctx)
	if err != nil {
		return err
	}
	puts := make([]Mutation, 0, len(keys))
	for _, key := range keys {
		parsed, parseErr := schema.ParseKey(key)
		if parseErr != nil || parsed.Kind != schema.KeyCrawlDebt {
			rollbackTransaction(ctx, transaction)
			return fmt.Errorf("invalid crawl-debt key")
		}
		value, found, getErr := transaction.Get(ctx, key)
		if getErr != nil {
			rollbackTransaction(ctx, transaction)
			return getErr
		}
		if !found {
			continue
		}
		debt, decodeErr := schema.UnmarshalCrawlDebtRecord(value)
		if decodeErr != nil {
			rollbackTransaction(ctx, transaction)
			return decodeErr
		}
		if debt.Status == schema.DebtResolved {
			continue
		}
		debt.Status = schema.DebtResolved
		debt.ErrorClass = ""
		debt.LastAttemptUnixNano = time.Now().UnixNano()
		encoded, encodeErr := debt.MarshalBinary()
		if encodeErr != nil {
			rollbackTransaction(ctx, transaction)
			return encodeErr
		}
		puts = append(puts, Mutation{Key: key, Value: encoded})
	}
	if err := writeTransactionBatches(ctx, transaction, store.client.Limits(), puts, nil); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	if err := transaction.Commit(ctx); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	return nil
}

func (store *SchemaStore) recordCrawlDebtFailureOnce(ctx context.Context, keys [][]byte, errorClass string) error {
	transaction, err := store.client.Begin(ctx)
	if err != nil {
		return err
	}
	puts := make([]Mutation, 0, len(keys))
	for _, key := range keys {
		parsed, parseErr := schema.ParseKey(key)
		if parseErr != nil || parsed.Kind != schema.KeyCrawlDebt {
			rollbackTransaction(ctx, transaction)
			return fmt.Errorf("invalid crawl-debt key")
		}
		value, found, getErr := transaction.Get(ctx, key)
		if getErr != nil {
			rollbackTransaction(ctx, transaction)
			return getErr
		}
		if !found {
			continue
		}
		debt, decodeErr := schema.UnmarshalCrawlDebtRecord(value)
		if decodeErr != nil {
			rollbackTransaction(ctx, transaction)
			return decodeErr
		}
		if debt.Status == schema.DebtResolved {
			continue
		}
		if debt.RetryCount < math.MaxUint32 {
			debt.RetryCount++
		}
		debt.Status = schema.DebtPending
		debt.LastAttemptUnixNano = time.Now().UnixNano()
		debt.ErrorClass = errorClass
		encoded, encodeErr := debt.MarshalBinary()
		if encodeErr != nil {
			rollbackTransaction(ctx, transaction)
			return encodeErr
		}
		puts = append(puts, Mutation{Key: key, Value: encoded})
	}
	if err := writeTransactionBatches(ctx, transaction, store.client.Limits(), puts, nil); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	if err := transaction.Commit(ctx); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	return nil
}

// ImportLegacyPack atomically merges one legacy pack's blob locations,
// provenance, catalog record, aggregates, and optional pack-stat debt.
func (store *SchemaStore) ImportLegacyPack(ctx context.Context, imported LegacyPackImport) error {
	backoff := 100 * time.Microsecond
	for range revisionAllocationAttempts {
		err := store.importPackOnce(ctx, imported, true)
		if status.Code(err) != codes.Aborted {
			return err
		}
		timer := time.NewTimer(backoff)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
		}
		backoff = min(backoff*2, 25*time.Millisecond)
	}
	return fmt.Errorf("import legacy pack: %w", errors.New("transaction conflict retry limit exceeded"))
}

// PublishPack atomically merges a newly-written pack's catalog entry, blob
// locations, and aggregates. Retries are idempotent and preserve existing
// duplicate blob locations from other packs.
func (store *SchemaStore) PublishPack(ctx context.Context, published PublishedPack) error {
	imported := LegacyPackImport{PackID: published.PackID, Record: published.Record, Blobs: published.Blobs}
	backoff := 100 * time.Microsecond
	for range revisionAllocationAttempts {
		err := store.importPackOnce(ctx, imported, false)
		if status.Code(err) != codes.Aborted {
			return err
		}
		timer := time.NewTimer(backoff)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
		}
		backoff = min(backoff*2, 25*time.Millisecond)
	}
	return fmt.Errorf("publish pack: transaction conflict retry limit exceeded")
}

func (store *SchemaStore) importPackOnce(ctx context.Context, imported LegacyPackImport, legacy bool) error {
	if imported.PackID == (schema.ID{}) || (legacy && imported.SourceIndex == (schema.ID{})) {
		return fmt.Errorf("pack publication requires its identity%s", map[bool]string{true: " and source index", false: ""}[legacy])
	}
	wantLifecycle := schema.PackExportPending
	if legacy {
		wantLifecycle = schema.PackImported
	}
	if imported.Record.Lifecycle != wantLifecycle {
		return fmt.Errorf("pack publication has invalid lifecycle")
	}
	locationTypes := make([]schema.BlobType, 0, imported.Record.BlobCount)
	var locationCount uint64
	for blobID, blob := range imported.Blobs {
		blob = canonicalBlobRecord(blob)
		imported.Blobs[blobID] = blob
		for _, location := range blob.Locations {
			if location.PackID != imported.PackID {
				return fmt.Errorf("legacy blob location belongs to a different pack")
			}
			locationTypes = append(locationTypes, location.Type)
			locationCount++
		}
	}
	if locationCount != imported.Record.BlobCount || schema.ClassifyPack(locationTypes) != imported.Record.Type {
		return fmt.Errorf("legacy pack record does not match its blob locations")
	}
	transaction, err := store.client.Begin(ctx)
	if err != nil {
		return err
	}
	fail := func(err error) error {
		rollbackTransaction(ctx, transaction)
		return err
	}

	packKey := schema.PackKey(imported.PackID)
	packValue, packFound, err := transaction.Get(ctx, packKey)
	if err != nil {
		return fail(err)
	}
	var oldRecord *schema.PackRecord
	if packFound {
		record, decodeErr := schema.UnmarshalPackRecord(packValue)
		if decodeErr != nil {
			return fail(decodeErr)
		}
		oldRecord = &record
		imported.Record = mergeImportedPackRecord(record, imported.Record, imported.SourceIndex, legacy)
	} else {
		if legacy {
			imported.Record.SourceIndexIDs = appendUniqueID(imported.Record.SourceIndexIDs, imported.SourceIndex)
		}
	}
	sort.Slice(imported.Record.SourceIndexIDs, func(left, right int) bool {
		return bytes.Compare(imported.Record.SourceIndexIDs[left][:], imported.Record.SourceIndexIDs[right][:]) < 0
	})

	puts := make([]Mutation, 0, len(imported.Blobs)+7)
	var newLocationCount, newPayloadSize uint64
	for blobID, incoming := range imported.Blobs {
		key := schema.BlobKey(blobID)
		value, found, getErr := transaction.Get(ctx, key)
		if getErr != nil {
			return fail(getErr)
		}
		if found {
			existing, decodeErr := schema.UnmarshalBlobRecord(value)
			if decodeErr != nil {
				return fail(decodeErr)
			}
			for _, location := range incoming.Locations {
				if !containsPhysicalLocation(existing.Locations, location) {
					newLocationCount++
					if math.MaxUint64-newPayloadSize < uint64(location.Length) {
						return fail(fmt.Errorf("pack payload size overflow"))
					}
					newPayloadSize += uint64(location.Length)
				}
			}
			incoming = mergeBlobRecords(existing, incoming)
		} else {
			newLocationCount += uint64(len(incoming.Locations))
			for _, location := range incoming.Locations {
				if math.MaxUint64-newPayloadSize < uint64(location.Length) {
					return fail(fmt.Errorf("pack payload size overflow"))
				}
				newPayloadSize += uint64(location.Length)
			}
		}
		incoming = canonicalBlobRecord(incoming)
		encoded, encodeErr := incoming.MarshalBinary()
		if encodeErr != nil {
			return fail(encodeErr)
		}
		puts = append(puts, Mutation{Key: key, Value: encoded})
	}
	if oldRecord != nil {
		if math.MaxUint64-oldRecord.BlobCount < newLocationCount || math.MaxUint64-oldRecord.PayloadSize < newPayloadSize {
			return fail(fmt.Errorf("pack catalog size overflow"))
		}
		imported.Record.BlobCount = oldRecord.BlobCount + newLocationCount
		imported.Record.PayloadSize = oldRecord.PayloadSize + newPayloadSize
	}
	if imported.Record.PhysicalSizeKnown {
		if imported.Record.PhysicalSize < imported.Record.PayloadSize {
			imported.Record.HeaderSize = 0
		} else {
			imported.Record.HeaderSize = imported.Record.PhysicalSize - imported.Record.PayloadSize
		}
	}
	encodedPack, err := imported.Record.MarshalBinary()
	if err != nil {
		return fail(err)
	}
	puts = append(puts, Mutation{Key: packKey, Value: encodedPack})

	aggregates, err := updatePackAggregates(ctx, transaction, oldRecord, imported.Record)
	if err != nil {
		return fail(err)
	}
	puts = append(puts, aggregates...)
	if imported.Debt != nil {
		if len(imported.DebtKey) == 0 {
			return fail(fmt.Errorf("legacy pack debt requires a key"))
		}
		debtValue, encodeErr := imported.Debt.MarshalBinary()
		if encodeErr != nil {
			return fail(encodeErr)
		}
		if encodeErr = schema.ValidateValue(imported.DebtKey, debtValue); encodeErr != nil {
			return fail(encodeErr)
		}
		puts = append(puts, Mutation{Key: imported.DebtKey, Value: debtValue})
	} else {
		debtKey := schema.CrawlDebtKey(schema.ID{}, imported.PackID)
		debtValue, found, getErr := transaction.Get(ctx, debtKey)
		if getErr != nil {
			return fail(getErr)
		}
		if found {
			debt, decodeErr := schema.UnmarshalCrawlDebtRecord(debtValue)
			if decodeErr != nil {
				return fail(decodeErr)
			}
			if debt.Reason == schema.DebtUnavailablePack && debt.Status != schema.DebtResolved {
				debt.Status = schema.DebtResolved
				debt.ErrorClass = ""
				debt.LastAttemptUnixNano = time.Now().UnixNano()
				encoded, encodeErr := debt.MarshalBinary()
				if encodeErr != nil {
					return fail(encodeErr)
				}
				puts = append(puts, Mutation{Key: debtKey, Value: encoded})
			}
		}
	}
	limits := store.client.Limits()
	if imported.BatchSize > 0 && imported.BatchSize < limits.MaxBatchItems {
		limits.MaxBatchItems = imported.BatchSize
	}
	if err := writeTransactionBatches(ctx, transaction, limits, puts, nil); err != nil {
		return fail(err)
	}
	if err := transaction.Commit(ctx); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	return nil
}

func (store *SchemaStore) MarkPackPublished(ctx context.Context, packID schema.ID) error {
	backoff := 100 * time.Microsecond
	for range revisionAllocationAttempts {
		err := store.markPackPublishedOnce(ctx, packID)
		if status.Code(err) != codes.Aborted {
			return err
		}
		timer := time.NewTimer(backoff)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
		}
		backoff = min(backoff*2, 25*time.Millisecond)
	}
	return fmt.Errorf("mark pack published: transaction conflict retry limit exceeded")
}

func (store *SchemaStore) MarkIndexPublished(ctx context.Context, indexID schema.ID, packIDs []schema.ID) (uint64, error) {
	backoff := 100 * time.Microsecond
	for range revisionAllocationAttempts {
		sequence, err := store.markIndexPublishedOnce(ctx, indexID, packIDs)
		if status.Code(err) != codes.Aborted {
			return sequence, err
		}
		timer := time.NewTimer(backoff)
		select {
		case <-ctx.Done():
			timer.Stop()
			return 0, ctx.Err()
		case <-timer.C:
		}
		backoff = min(backoff*2, 25*time.Millisecond)
	}
	return 0, fmt.Errorf("mark index published: transaction conflict retry limit exceeded")
}

func (store *SchemaStore) markIndexPublishedOnce(ctx context.Context, indexID schema.ID, packIDs []schema.ID) (uint64, error) {
	if indexID == (schema.ID{}) || len(packIDs) == 0 {
		return 0, fmt.Errorf("export index and pack IDs are required")
	}
	packIDs = append([]schema.ID(nil), packIDs...)
	sort.Slice(packIDs, func(left, right int) bool { return bytes.Compare(packIDs[left][:], packIDs[right][:]) < 0 })
	transaction, err := store.client.Begin(ctx)
	if err != nil {
		return 0, err
	}
	fail := func(err error) (uint64, error) {
		rollbackTransaction(ctx, transaction)
		return 0, err
	}
	checkpointKey := schema.ExportIndexCheckpointKey(indexID)
	checkpointValue, found, err := transaction.Get(ctx, checkpointKey)
	if err != nil {
		return fail(err)
	}
	var checkpoint schema.ExportIndexCheckpointRecord
	puts := make([]Mutation, 0, len(packIDs)+2)
	if found {
		checkpoint, err = schema.UnmarshalExportIndexCheckpointRecord(checkpointValue)
		if err != nil || !slices.Equal(checkpoint.PackIDs, packIDs) {
			return fail(fmt.Errorf("export index checkpoint conflicts with pack provenance"))
		}
	} else {
		nextValue, nextFound, getErr := transaction.Get(ctx, schema.NextExportSequenceKey())
		if getErr != nil {
			return fail(getErr)
		}
		next := uint64(1)
		if nextFound {
			next, err = schema.UnmarshalNextExportSequence(nextValue)
			if err != nil {
				return fail(err)
			}
		}
		if next == math.MaxUint64 {
			return fail(fmt.Errorf("export sequence overflow"))
		}
		checkpoint = schema.ExportIndexCheckpointRecord{Sequence: next, PackIDs: packIDs}
		checkpointValue, err = checkpoint.MarshalBinary()
		if err != nil {
			return fail(err)
		}
		encodedNext, encodeErr := schema.MarshalNextExportSequence(next + 1)
		if encodeErr != nil {
			return fail(encodeErr)
		}
		puts = append(puts, Mutation{Key: checkpointKey, Value: checkpointValue}, Mutation{Key: schema.NextExportSequenceKey(), Value: encodedNext})
	}
	for _, packID := range packIDs {
		key := schema.PackKey(packID)
		value, packFound, getErr := transaction.Get(ctx, key)
		if getErr != nil {
			return fail(getErr)
		}
		if !packFound {
			return fail(fmt.Errorf("published pack is missing"))
		}
		record, decodeErr := schema.UnmarshalPackRecord(value)
		if decodeErr != nil {
			return fail(decodeErr)
		}
		if record.Lifecycle != schema.PackPublished {
			if record.Lifecycle != schema.PackExportPending && record.Lifecycle != schema.PackImported {
				return fail(fmt.Errorf("pack cannot transition from lifecycle %d to published", record.Lifecycle))
			}
			record.Lifecycle = schema.PackPublished
			encoded, encodeErr := record.MarshalBinary()
			if encodeErr != nil {
				return fail(encodeErr)
			}
			puts = append(puts, Mutation{Key: key, Value: encoded})
		}
	}
	if err := writeTransactionBatches(ctx, transaction, store.client.Limits(), puts, nil); err != nil {
		return fail(err)
	}
	if err := transaction.Commit(ctx); err != nil {
		rollbackTransaction(ctx, transaction)
		return 0, err
	}
	return checkpoint.Sequence, nil
}

func (store *SchemaStore) markPackPublishedOnce(ctx context.Context, packID schema.ID) error {
	key := schema.PackKey(packID)
	transaction, err := store.client.Begin(ctx)
	if err != nil {
		return err
	}
	fail := func(err error) error {
		rollbackTransaction(ctx, transaction)
		return err
	}
	value, found, err := transaction.Get(ctx, key)
	if err != nil {
		return fail(err)
	}
	if !found {
		return fail(fmt.Errorf("published pack is missing"))
	}
	record, err := schema.UnmarshalPackRecord(value)
	if err != nil {
		return fail(err)
	}
	if record.Lifecycle == schema.PackPublished {
		return transaction.Rollback(ctx)
	}
	if record.Lifecycle != schema.PackExportPending && record.Lifecycle != schema.PackImported {
		return fail(fmt.Errorf("pack cannot transition from lifecycle %d to published", record.Lifecycle))
	}
	record.Lifecycle = schema.PackPublished
	encoded, err := record.MarshalBinary()
	if err != nil {
		return fail(err)
	}
	if err := transaction.WriteBatch(ctx, []Mutation{{Key: key, Value: encoded}}, nil); err != nil {
		return fail(err)
	}
	if err := transaction.Commit(ctx); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	return nil
}

func mergeBlobRecords(existing, incoming schema.BlobRecord) schema.BlobRecord {
	result := schema.BlobRecord{Locations: append([]schema.BlobLocation(nil), existing.Locations...)}
	for _, candidate := range incoming.Locations {
		found := false
		for index, location := range result.Locations {
			if samePhysicalLocation(location, candidate) {
				if candidate.UncompressedSize > location.UncompressedSize {
					result.Locations[index].UncompressedSize = candidate.UncompressedSize
				}
				found = true
				break
			}
		}
		if !found {
			result.Locations = append(result.Locations, candidate)
		}
	}
	return canonicalBlobRecord(result)
}

func canonicalBlobRecord(record schema.BlobRecord) schema.BlobRecord {
	canonical := make([]schema.BlobLocation, 0, len(record.Locations))
	for _, candidate := range record.Locations {
		merged := false
		for index, location := range canonical {
			if samePhysicalLocation(location, candidate) {
				if candidate.UncompressedSize > location.UncompressedSize {
					canonical[index].UncompressedSize = candidate.UncompressedSize
				}
				merged = true
				break
			}
		}
		if !merged {
			canonical = append(canonical, candidate)
		}
	}
	record.Locations = canonical
	sort.Slice(record.Locations, func(left, right int) bool {
		leftLocation, rightLocation := record.Locations[left], record.Locations[right]
		if comparison := bytes.Compare(leftLocation.PackID[:], rightLocation.PackID[:]); comparison != 0 {
			return comparison < 0
		}
		if leftLocation.Type != rightLocation.Type {
			return leftLocation.Type < rightLocation.Type
		}
		if leftLocation.Offset != rightLocation.Offset {
			return leftLocation.Offset < rightLocation.Offset
		}
		if leftLocation.Length != rightLocation.Length {
			return leftLocation.Length < rightLocation.Length
		}
		return leftLocation.UncompressedSize < rightLocation.UncompressedSize
	})
	return record
}

func samePhysicalLocation(left, right schema.BlobLocation) bool {
	return left.PackID == right.PackID && left.Offset == right.Offset && left.Length == right.Length && left.Type == right.Type
}

func containsPhysicalLocation(locations []schema.BlobLocation, candidate schema.BlobLocation) bool {
	for _, location := range locations {
		if samePhysicalLocation(location, candidate) {
			return true
		}
	}
	return false
}

func appendUniqueID(ids []schema.ID, candidate schema.ID) []schema.ID {
	for _, id := range ids {
		if id == candidate {
			return ids
		}
	}
	return append(ids, candidate)
}

func mergeImportedPackRecord(existing, incoming schema.PackRecord, source schema.ID, includeSource bool) schema.PackRecord {
	result := existing
	if includeSource {
		result.SourceIndexIDs = appendUniqueID(result.SourceIndexIDs, source)
	}
	for _, sourceIndex := range incoming.SourceIndexIDs {
		result.SourceIndexIDs = appendUniqueID(result.SourceIndexIDs, sourceIndex)
	}
	if incoming.PhysicalSizeKnown {
		result.PhysicalSize = incoming.PhysicalSize
		result.HeaderSize = incoming.HeaderSize
		result.PhysicalSizeKnown = true
	}
	if result.Type != incoming.Type {
		result.Type = schema.PackMixed
	}
	if existing.Type == schema.PackUnknown {
		result.Type = incoming.Type
	}
	if incoming.Type == schema.PackUnknown {
		result.Type = existing.Type
	}
	sort.Slice(result.SourceIndexIDs, func(left, right int) bool {
		return bytes.Compare(result.SourceIndexIDs[left][:], result.SourceIndexIDs[right][:]) < 0
	})
	return result
}

func updatePackAggregates(ctx context.Context, transaction *Transaction, old *schema.PackRecord, current schema.PackRecord) ([]Mutation, error) {
	keys := make([][]byte, 0, 5)
	for kind := schema.AggregateData; kind <= schema.AggregateAll; kind++ {
		keys = append(keys, schema.PackAggregateKey(kind))
	}
	values, found, err := transaction.MultiGet(ctx, keys)
	if err != nil {
		return nil, err
	}
	puts := make([]Mutation, 0, len(keys))
	for offset, key := range keys {
		kind := schema.AggregateKind(offset) + schema.AggregateData
		aggregate := schema.PackAggregate{}
		if found[offset] {
			aggregate, err = schema.UnmarshalPackAggregate(values[offset].Value)
			if err != nil {
				return nil, err
			}
		}
		if old != nil && (kind == schema.AggregateAll || aggregateKind(old.Type) == kind) {
			if err := subtractPackAggregate(&aggregate, *old); err != nil {
				return nil, err
			}
		}
		if kind == schema.AggregateAll || aggregateKind(current.Type) == kind {
			if err := addPackAggregate(&aggregate, current); err != nil {
				return nil, err
			}
		}
		aggregate.UpdateSequence++
		encoded, err := aggregate.MarshalBinary()
		if err != nil {
			return nil, err
		}
		puts = append(puts, Mutation{Key: key, Value: encoded})
	}
	return puts, nil
}

func aggregateKind(packType schema.PackType) schema.AggregateKind {
	return schema.AggregateKind(packType)
}

func subtractPackAggregate(aggregate *schema.PackAggregate, record schema.PackRecord) error {
	if aggregate.PackCount == 0 || aggregate.PhysicalSize < record.PhysicalSize || aggregate.PayloadSize < record.PayloadSize || aggregate.HeaderSize < record.HeaderSize || aggregate.BlobCount < record.BlobCount {
		return fmt.Errorf("pack aggregate underflow")
	}
	aggregate.PackCount--
	aggregate.PhysicalSize -= record.PhysicalSize
	aggregate.PayloadSize -= record.PayloadSize
	aggregate.HeaderSize -= record.HeaderSize
	aggregate.BlobCount -= record.BlobCount
	return nil
}

func addPackAggregate(aggregate *schema.PackAggregate, record schema.PackRecord) error {
	if aggregate.PackCount == math.MaxUint64 || math.MaxUint64-aggregate.PhysicalSize < record.PhysicalSize || math.MaxUint64-aggregate.PayloadSize < record.PayloadSize || math.MaxUint64-aggregate.HeaderSize < record.HeaderSize || math.MaxUint64-aggregate.BlobCount < record.BlobCount {
		return fmt.Errorf("pack aggregate overflow")
	}
	aggregate.PackCount++
	aggregate.PhysicalSize += record.PhysicalSize
	aggregate.PayloadSize += record.PayloadSize
	aggregate.HeaderSize += record.HeaderSize
	aggregate.BlobCount += record.BlobCount
	return nil
}

func (store *SchemaStore) Put(ctx context.Context, key, value []byte, durable bool) error {
	return store.WriteMutableBatch(ctx, []Mutation{{Key: key, Value: value}}, nil, durable)
}

// WriteMutableBatch atomically updates independently mutable schema records.
// Immutable records, current pointers, and the revision counter require their
// dedicated transactional operations.
func (store *SchemaStore) WriteMutableBatch(ctx context.Context, puts []Mutation, deletes [][]byte, durable bool) error {
	if err := validateDistinctMutations(puts, deletes); err != nil {
		return err
	}
	for _, put := range puts {
		if err := validateMutableKey(put.Key); err != nil {
			return err
		}
		if err := schema.ValidateValue(put.Key, put.Value); err != nil {
			return err
		}
	}
	for _, key := range deletes {
		if err := validateMutableDeleteKey(key); err != nil {
			return err
		}
	}
	acknowledged, err := store.client.WriteBatch(ctx, puts, deletes, durable, "")
	if err != nil {
		return err
	}
	if durable && !acknowledged {
		return fmt.Errorf("vaulticdb did not acknowledge durable schema write")
	}
	return nil
}

// PublishSchemaBatch atomically creates immutable records and updates mutable
// catalog, aggregate, reverse-index, GC, and crawl-debt records. Existing
// immutable values must match byte-for-byte.
func (store *SchemaStore) PublishSchemaBatch(ctx context.Context, puts []Mutation, deletes [][]byte) error {
	seen := make(map[string]struct{}, len(puts)+len(deletes))
	immutableKeys := make([][]byte, 0, len(puts))
	immutableIndexes := make([]int, 0, len(puts))
	for index, put := range puts {
		keyString := string(put.Key)
		if _, duplicate := seen[keyString]; duplicate {
			return fmt.Errorf("schema batch contains duplicate key")
		}
		seen[keyString] = struct{}{}
		immutable, err := validatePublishKey(put.Key)
		if err != nil {
			return err
		}
		if err := schema.ValidateValue(put.Key, put.Value); err != nil {
			return err
		}
		if immutable {
			immutableKeys = append(immutableKeys, put.Key)
			immutableIndexes = append(immutableIndexes, index)
		}
	}
	for _, key := range deletes {
		keyString := string(key)
		if _, duplicate := seen[keyString]; duplicate {
			return fmt.Errorf("schema batch contains duplicate key")
		}
		seen[keyString] = struct{}{}
		if err := validateMutableDeleteKey(key); err != nil {
			return err
		}
	}
	transaction, err := store.client.Begin(ctx)
	if err != nil {
		return err
	}
	remainingPuts := append([]Mutation(nil), puts...)
	if len(immutableKeys) > 0 {
		values, found, err := transaction.MultiGet(ctx, immutableKeys)
		if err != nil {
			rollbackTransaction(ctx, transaction)
			return err
		}
		remove := make(map[int]struct{})
		for offset, exists := range found {
			if !exists {
				continue
			}
			index := immutableIndexes[offset]
			if !bytes.Equal(values[offset].Value, puts[index].Value) {
				rollbackTransaction(ctx, transaction)
				return fmt.Errorf("immutable schema record already exists with different data")
			}
			remove[index] = struct{}{}
		}
		if len(remove) > 0 {
			remainingPuts = remainingPuts[:0]
			for index, put := range puts {
				if _, skip := remove[index]; !skip {
					remainingPuts = append(remainingPuts, put)
				}
			}
		}
	}
	if len(remainingPuts) == 0 && len(deletes) == 0 {
		return transaction.Rollback(ctx)
	}
	if err := writeTransactionBatches(ctx, transaction, store.client.Limits(), remainingPuts, deletes); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	if err := transaction.Commit(ctx); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	return nil
}

func validateMutableKey(key []byte) error {
	parsed, err := schema.ParseKey(key)
	if err != nil {
		return err
	}
	switch parsed.Kind {
	case schema.KeyPack, schema.KeyPackAggregate, schema.KeyReverseManifest, schema.KeyReverseInode,
		schema.KeyReferenceCount, schema.KeyGarbageCollection, schema.KeyCrawlDebt, schema.KeyImportCheckpoint,
		schema.KeySnapshotImportCheckpoint, schema.KeyExportCheckpoint:
		return nil
	case schema.KeyNextRevision:
		return fmt.Errorf("revision sequence requires AllocateRevision")
	default:
		return fmt.Errorf("schema key requires a dedicated transactional operation")
	}
}

func validateMutableDeleteKey(key []byte) error {
	parsed, err := schema.ParseKey(key)
	if err != nil {
		return err
	}
	switch parsed.Kind {
	case schema.KeyReverseManifest, schema.KeyReverseInode, schema.KeyReferenceCount:
		return nil
	default:
		return fmt.Errorf("schema key must remain visible and cannot be deleted")
	}
}

func validatePublishKey(key []byte) (bool, error) {
	parsed, err := schema.ParseKey(key)
	if err != nil {
		return false, err
	}
	switch parsed.Kind {
	case schema.KeyBlob, schema.KeyInodeRevision, schema.KeyDirectoryRevision, schema.KeySnapshot:
		return true, nil
	case schema.KeyPack, schema.KeyPackAggregate, schema.KeyReverseManifest, schema.KeyReverseInode,
		schema.KeyReferenceCount, schema.KeyGarbageCollection, schema.KeyCrawlDebt, schema.KeyImportCheckpoint,
		schema.KeySnapshotImportCheckpoint, schema.KeyExportCheckpoint:
		return false, nil
	case schema.KeyContentManifest:
		return false, fmt.Errorf("content manifests require CreateContentManifest")
	case schema.KeyNextRevision:
		return false, fmt.Errorf("revision sequence requires AllocateRevision")
	default:
		return false, fmt.Errorf("schema key requires a dedicated transactional operation")
	}
}

// MarkExportPending durably exposes a legacy snapshot whose authoritative
// scope has not yet been committed.
func (store *SchemaStore) MarkExportPending(ctx context.Context, snapshotID schema.ID, rootKey []byte) error {
	record := schema.ExportCheckpointRecord{State: schema.ExportPending, RootKey: append([]byte(nil), rootKey...)}
	encoded, err := record.MarshalBinary()
	if err != nil {
		return err
	}
	return store.Put(ctx, schema.ExportCheckpointKey(snapshotID), encoded, true)
}

func (store *SchemaStore) MarkExportFailed(ctx context.Context, snapshotID schema.ID, failure error) error {
	key := schema.ExportCheckpointKey(snapshotID)
	value, found, err := store.Get(ctx, key)
	if err != nil {
		return err
	}
	if !found {
		return fmt.Errorf("snapshot export checkpoint is missing")
	}
	record, err := schema.UnmarshalExportCheckpointRecord(value)
	if err != nil {
		return err
	}
	if record.State != schema.ExportPending {
		return fmt.Errorf("snapshot export cannot fail from state %d", record.State)
	}
	record.State = schema.ExportFailed
	record.Attempts++
	record.LastError = failure.Error()
	encoded, err := record.MarshalBinary()
	if err != nil {
		return err
	}
	return store.Put(ctx, key, encoded, true)
}

// PublishSnapshotScope verifies that the reconciled root is durable, allocates
// a commit sequence, creates the immutable snapshot record, and completes its
// export checkpoint in one serializable transaction.
func (store *SchemaStore) PublishSnapshotScope(ctx context.Context, scope SnapshotScope) error {
	root, err := schema.ParseKey(scope.RootKey)
	if err != nil || root.Kind != schema.KeyDirectoryRevision || root.Revision == 0 || scope.SnapshotID == (schema.ID{}) {
		return fmt.Errorf("invalid snapshot scope")
	}
	backoff := 100 * time.Microsecond
	for range revisionAllocationAttempts {
		err := store.publishSnapshotScopeOnce(ctx, scope, root)
		if status.Code(err) != codes.Aborted {
			return err
		}
		timer := time.NewTimer(backoff)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
		}
		backoff = min(backoff*2, 25*time.Millisecond)
	}
	return fmt.Errorf("publish snapshot scope: transaction conflict retry limit exceeded")
}

func (store *SchemaStore) publishSnapshotScopeOnce(ctx context.Context, scope SnapshotScope, root schema.ParsedKey) error {
	transaction, err := store.client.Begin(ctx)
	if err != nil {
		return err
	}
	fail := func(err error) error { rollbackTransaction(ctx, transaction); return err }
	if _, found, err := transaction.Get(ctx, scope.RootKey); err != nil {
		return fail(err)
	} else if !found {
		return fail(fmt.Errorf("snapshot root revision is not durable"))
	}
	checkpointKey := schema.ExportCheckpointKey(scope.SnapshotID)
	if value, found, err := transaction.Get(ctx, checkpointKey); err != nil {
		return fail(err)
	} else if !found {
		return fail(fmt.Errorf("snapshot export checkpoint is missing"))
	} else if checkpoint, decodeErr := schema.UnmarshalExportCheckpointRecord(value); decodeErr != nil || checkpoint.State != schema.ExportPending {
		if decodeErr != nil {
			return fail(decodeErr)
		}
		return transaction.Rollback(ctx)
	}
	nextKey := schema.NextRevisionKey()
	next := uint64(1)
	if value, found, err := transaction.Get(ctx, nextKey); err != nil {
		return fail(err)
	} else if found {
		next, err = schema.UnmarshalNextRevision(value)
		if err != nil {
			return fail(err)
		}
	}
	if next == math.MaxUint64 {
		return fail(fmt.Errorf("repository revision sequence exhausted"))
	}
	record := schema.SnapshotRecord{CommitSequence: next, RootFSID: root.FSID, RootInode: root.Inode, RootRevision: root.Revision, OriginalJSON: append([]byte(nil), scope.OriginalJSON...)}
	snapshotValue, err := record.MarshalBinary()
	if err != nil {
		return fail(err)
	}
	checkpointValue, err := (schema.ExportCheckpointRecord{State: schema.ExportComplete, CommitSequence: next, Attempts: 1, RootKey: scope.RootKey}).MarshalBinary()
	if err != nil {
		return fail(err)
	}
	nextValue, err := schema.MarshalNextRevision(next + 1)
	if err != nil {
		return fail(err)
	}
	puts := []Mutation{{Key: schema.SnapshotKey(scope.SnapshotID), Value: snapshotValue}, {Key: checkpointKey, Value: checkpointValue}, {Key: nextKey, Value: nextValue}}
	if err := writeTransactionBatches(ctx, transaction, store.client.Limits(), puts, nil); err != nil {
		return fail(err)
	}
	if err := transaction.Commit(ctx); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	return nil
}

// CreateImmutable creates a historical record or verifies an identical retry.
// It never overwrites an existing key with different bytes.
func (store *SchemaStore) CreateImmutable(ctx context.Context, key, value []byte) error {
	parsed, err := schema.ParseKey(key)
	if err != nil {
		return err
	}
	switch parsed.Kind {
	case schema.KeyBlob, schema.KeyInodeRevision, schema.KeyDirectoryRevision, schema.KeySnapshot:
	case schema.KeyContentManifest:
		return fmt.Errorf("content manifests require CreateContentManifest")
	default:
		return fmt.Errorf("schema key is mutable and cannot use CreateImmutable")
	}
	if err := schema.ValidateValue(key, value); err != nil {
		return err
	}
	transaction, err := store.client.Begin(ctx)
	if err != nil {
		return err
	}
	existing, found, err := transaction.Get(ctx, key)
	if err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	if found {
		if rollbackErr := rollbackTransaction(ctx, transaction); rollbackErr != nil {
			return rollbackErr
		}
		if !bytes.Equal(existing, value) {
			return fmt.Errorf("immutable schema record already exists with different data")
		}
		return nil
	}
	if err := transaction.WriteBatch(ctx, []Mutation{{Key: key, Value: value}}, nil); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	if err := transaction.Commit(ctx); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	return nil
}

// CreateContentManifest atomically creates every immutable segment for one
// content-addressed ordered blob sequence, or verifies an identical retry.
func (store *SchemaStore) CreateContentManifest(ctx context.Context, ids []schema.ID) (schema.ID, error) {
	return store.PublishContentManifest(ctx, ids, nil, nil)
}

// PublishContentManifest atomically creates canonical immutable segments and
// applies their mutable reverse-reference updates.
func (store *SchemaStore) PublishContentManifest(ctx context.Context, ids []schema.ID, relatedPuts []Mutation, relatedDeletes [][]byte) (schema.ID, error) {
	if err := validateRelatedMutations(relatedPuts, relatedDeletes); err != nil {
		return schema.ID{}, err
	}
	manifestID, segments, err := schema.SegmentContent(ids, schema.DefaultContentSegmentIDs)
	if err != nil {
		return schema.ID{}, err
	}
	if _, err := schema.AssembleContent(manifestID, append([]schema.ContentManifest(nil), segments...)); err != nil {
		return schema.ID{}, err
	}
	keys := make([][]byte, len(segments))
	encoded := make([][]byte, len(segments))
	for index, segment := range segments {
		keys[index] = schema.ContentManifestKey(manifestID, uint32(index))
		encoded[index], err = segment.MarshalBinary()
		if err != nil {
			return schema.ID{}, err
		}
	}
	transaction, err := store.client.Begin(ctx)
	if err != nil {
		return schema.ID{}, err
	}
	for start := 0; start < len(keys); {
		end, err := manifestBatchEnd(store.client.Limits(), keys, encoded, start)
		if err != nil {
			rollbackTransaction(ctx, transaction)
			return schema.ID{}, err
		}
		values, found, err := transaction.MultiGet(ctx, keys[start:end])
		if err != nil {
			rollbackTransaction(ctx, transaction)
			return schema.ID{}, err
		}
		puts := make([]Mutation, 0, end-start)
		for offset := range keys[start:end] {
			index := start + offset
			if found[offset] {
				if !bytes.Equal(values[offset].Value, encoded[index]) {
					rollbackTransaction(ctx, transaction)
					return schema.ID{}, fmt.Errorf("immutable content manifest segment already exists with different data")
				}
				continue
			}
			puts = append(puts, Mutation{Key: keys[index], Value: encoded[index]})
		}
		if len(puts) > 0 {
			if err := transaction.WriteBatch(ctx, puts, nil); err != nil {
				rollbackTransaction(ctx, transaction)
				return schema.ID{}, err
			}
		}
		start = end
	}
	if len(relatedPuts) > 0 || len(relatedDeletes) > 0 {
		if err := writeTransactionBatches(ctx, transaction, store.client.Limits(), relatedPuts, relatedDeletes); err != nil {
			rollbackTransaction(ctx, transaction)
			return schema.ID{}, err
		}
	}
	if err := transaction.Commit(ctx); err != nil {
		rollbackTransaction(ctx, transaction)
		return schema.ID{}, err
	}
	return manifestID, nil
}

func manifestBatchEnd(limits Limits, keys, values [][]byte, start int) (int, error) {
	if limits.MaxBatchItems == 0 || limits.MaxMessageBytes < 128 {
		return 0, fmt.Errorf("vaulticdb advertised insufficient manifest batch limits")
	}
	maxBytes := uint64(limits.MaxMessageBytes) / 2
	used := uint64(0)
	end := start
	for end < len(keys) && uint64(end-start) < uint64(limits.MaxBatchItems) {
		size := uint64(len(keys[end])) + uint64(len(values[end])) + 32
		if size > maxBytes {
			return 0, fmt.Errorf("content manifest segment exceeds daemon message limit")
		}
		if used+size > maxBytes {
			break
		}
		used += size
		end++
	}
	if end == start {
		return 0, fmt.Errorf("content manifest batch made no progress")
	}
	return end, nil
}

// PublishRevision atomically creates an immutable revision and advances its
// current pointer. A retry with identical revision bytes is idempotent.
func (store *SchemaStore) PublishRevision(ctx context.Context, currentKey, revisionKey, revisionValue []byte, revision uint64) error {
	return store.PublishRevisionBatch(ctx, currentKey, revisionKey, revisionValue, revision, nil, nil)
}

// PublishRevisionBatch atomically creates an immutable revision, advances its
// current pointer, and applies corresponding mutable reverse-reference data.
func (store *SchemaStore) PublishRevisionBatch(ctx context.Context, currentKey, revisionKey, revisionValue []byte, revision uint64, relatedPuts []Mutation, relatedDeletes [][]byte) error {
	if err := validateRelatedMutations(relatedPuts, relatedDeletes); err != nil {
		return err
	}
	current, err := schema.CurrentPointer{Revision: revision, RecordKey: revisionKey}.MarshalBinary()
	if err != nil {
		return err
	}
	currentParsed, err := schema.ParseKey(currentKey)
	if err != nil {
		return err
	}
	parsed, err := schema.ParseKey(revisionKey)
	validPair := currentParsed.FSID == parsed.FSID && currentParsed.Inode == parsed.Inode &&
		((currentParsed.Kind == schema.KeyCurrentInode && parsed.Kind == schema.KeyInodeRevision) ||
			(currentParsed.Kind == schema.KeyCurrentDirectory && parsed.Kind == schema.KeyDirectoryRevision))
	if err != nil || parsed.Revision != revision || !validPair {
		return fmt.Errorf("revision key does not match revision %d", revision)
	}
	if err := schema.ValidateValue(revisionKey, revisionValue); err != nil {
		return err
	}
	transaction, err := store.client.Begin(ctx)
	if err != nil {
		return err
	}
	existing, found, err := transaction.Get(ctx, revisionKey)
	if err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	if found && !bytes.Equal(existing, revisionValue) {
		rollbackTransaction(ctx, transaction)
		return fmt.Errorf("immutable revision already exists with different data")
	}
	currentValue, currentFound, err := transaction.Get(ctx, currentKey)
	if err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	if currentFound {
		pointer, decodeErr := schema.UnmarshalCurrentPointer(currentValue)
		if decodeErr != nil {
			rollbackTransaction(ctx, transaction)
			return decodeErr
		}
		if pointer.Revision > revision {
			rollbackTransaction(ctx, transaction)
			return fmt.Errorf("current revision %d is newer than %d", pointer.Revision, revision)
		}
	}
	puts := []Mutation{{Key: currentKey, Value: current}}
	if !found {
		puts = append(puts, Mutation{Key: revisionKey, Value: revisionValue})
	}
	puts = append(puts, relatedPuts...)
	if err := writeTransactionBatches(ctx, transaction, store.client.Limits(), puts, relatedDeletes); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	if err := transaction.Commit(ctx); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	return nil
}

// PublishReconciledRevision atomically publishes a verified metadata revision,
// content manifests, reverse references, reference counters, and debt
// resolution. Serializable conflicts retry the complete read/modify/write.
func (store *SchemaStore) PublishReconciledRevision(ctx context.Context, reconciled ReconciledRevision) error {
	backoff := 100 * time.Microsecond
	for range revisionAllocationAttempts {
		err := store.publishReconciledRevisionOnce(ctx, reconciled)
		if status.Code(err) != codes.Aborted {
			return err
		}
		timer := time.NewTimer(backoff)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
		}
		backoff = min(backoff*2, 25*time.Millisecond)
	}
	return fmt.Errorf("publish reconciled revision: transaction conflict retry limit exceeded")
}

func (store *SchemaStore) publishReconciledRevisionOnce(ctx context.Context, reconciled ReconciledRevision) error {
	currentValue, err := (schema.CurrentPointer{Revision: reconciled.Revision, RecordKey: reconciled.RevisionKey}).MarshalBinary()
	if err != nil {
		return err
	}
	currentParsed, err := schema.ParseKey(reconciled.CurrentKey)
	if err != nil {
		return err
	}
	revisionParsed, err := schema.ParseKey(reconciled.RevisionKey)
	if err != nil || reconciled.Revision == 0 || revisionParsed.Revision != reconciled.Revision ||
		currentParsed.FSID != revisionParsed.FSID || currentParsed.Inode != revisionParsed.Inode ||
		!((currentParsed.Kind == schema.KeyCurrentInode && revisionParsed.Kind == schema.KeyInodeRevision) ||
			(currentParsed.Kind == schema.KeyCurrentDirectory && revisionParsed.Kind == schema.KeyDirectoryRevision)) {
		return fmt.Errorf("reconciled revision key mismatch")
	}
	if err := schema.ValidateValue(reconciled.RevisionKey, reconciled.RevisionValue); err != nil {
		return err
	}
	if currentParsed.Kind == schema.KeyCurrentDirectory && len(reconciled.ContentIDs) != 0 {
		return fmt.Errorf("directory reconciliation cannot contain file content")
	}
	for _, key := range reconciled.DebtKeys {
		parsed, parseErr := schema.ParseKey(key)
		if parseErr != nil || parsed.Kind != schema.KeyCrawlDebt {
			return fmt.Errorf("reconciliation debt key is invalid")
		}
	}

	transaction, err := store.client.Begin(ctx)
	if err != nil {
		return err
	}
	fail := func(err error) error {
		rollbackTransaction(ctx, transaction)
		return err
	}
	existingRevision, revisionFound, err := transaction.Get(ctx, reconciled.RevisionKey)
	if err != nil {
		return fail(err)
	}
	if revisionFound && !bytes.Equal(existingRevision, reconciled.RevisionValue) {
		return fail(fmt.Errorf("immutable revision already exists with different data"))
	}

	var oldContent []schema.ID
	var oldManifestID schema.ID
	oldCurrent, currentFound, err := transaction.Get(ctx, reconciled.CurrentKey)
	if err != nil {
		return fail(err)
	}
	if currentFound {
		pointer, decodeErr := schema.UnmarshalCurrentPointer(oldCurrent)
		if decodeErr != nil {
			return fail(decodeErr)
		}
		if revisionFound && pointer.Revision == reconciled.Revision && bytes.Equal(pointer.RecordKey, reconciled.RevisionKey) {
			return transaction.Rollback(ctx)
		}
		if pointer.Revision > reconciled.Revision {
			return fail(fmt.Errorf("current revision %d is newer than %d", pointer.Revision, reconciled.Revision))
		}
		if currentParsed.Kind == schema.KeyCurrentInode {
			value, found, getErr := transaction.Get(ctx, pointer.RecordKey)
			if getErr != nil {
				return fail(getErr)
			}
			if !found {
				return fail(fmt.Errorf("current inode revision is missing"))
			}
			record, decodeErr := schema.UnmarshalInodeRevision(value)
			if decodeErr != nil {
				return fail(decodeErr)
			}
			oldContent, err = transactionContentIDs(ctx, transaction, record)
			if err != nil {
				return fail(err)
			}
			if record.ContentMode == schema.ContentManifestRef {
				oldManifestID = record.ContentManifestID
			}
		}
	}

	puts := map[string]Mutation{string(reconciled.CurrentKey): {Key: reconciled.CurrentKey, Value: currentValue}}
	if !revisionFound {
		puts[string(reconciled.RevisionKey)] = Mutation{Key: reconciled.RevisionKey, Value: reconciled.RevisionValue}
	}
	manifestID, segments, err := reconciledManifest(reconciled.ContentIDs)
	if err != nil {
		return fail(err)
	}
	for index, segment := range segments {
		key := schema.ContentManifestKey(manifestID, uint32(index))
		encoded, encodeErr := segment.MarshalBinary()
		if encodeErr != nil {
			return fail(encodeErr)
		}
		existing, found, getErr := transaction.Get(ctx, key)
		if getErr != nil {
			return fail(getErr)
		}
		if found && !bytes.Equal(existing, encoded) {
			return fail(fmt.Errorf("immutable content manifest segment already exists with different data"))
		}
		if !found {
			puts[string(key)] = Mutation{Key: key, Value: encoded}
		}
	}

	oldUnique := uniqueSchemaIDs(oldContent)
	newUnique := uniqueSchemaIDs(reconciled.ContentIDs)
	newSet := make(map[schema.ID]struct{}, len(newUnique))
	for _, id := range newUnique {
		newSet[id] = struct{}{}
	}
	for _, id := range oldUnique {
		if _, remains := newSet[id]; remains {
			continue
		}
		key := schema.ReverseInodeKey(id, currentParsed.FSID, currentParsed.Inode)
		value, encodeErr := (schema.ReverseInodeRecord{LatestRevision: reconciled.Revision, State: schema.ReferenceHistorical}).MarshalBinary()
		if encodeErr != nil {
			return fail(encodeErr)
		}
		puts[string(key)] = Mutation{Key: key, Value: value}
		countKey := schema.ReferenceCountKey(id)
		count, countErr := transactionReferenceCount(ctx, transaction, puts, countKey)
		if countErr != nil {
			return fail(countErr)
		}
		count.UpdateSequence = reconciled.Revision
		encoded, encodeErr := count.MarshalBinary()
		if encodeErr != nil {
			return fail(encodeErr)
		}
		puts[string(countKey)] = Mutation{Key: countKey, Value: encoded}
	}
	if oldManifestID != (schema.ID{}) && oldManifestID != manifestID {
		for _, id := range oldUnique {
			key := schema.ReverseManifestKey(id, oldManifestID)
			value, found, getErr := transaction.Get(ctx, key)
			if getErr != nil {
				return fail(getErr)
			}
			if !found {
				continue
			}
			reverse, decodeErr := schema.UnmarshalReverseManifestRecord(value)
			if decodeErr != nil {
				return fail(decodeErr)
			}
			reverse.State = schema.ReferenceHistorical
			encoded, encodeErr := reverse.MarshalBinary()
			if encodeErr != nil {
				return fail(encodeErr)
			}
			puts[string(key)] = Mutation{Key: key, Value: encoded}
		}
	}
	for _, id := range newUnique {
		key := schema.ReverseInodeKey(id, currentParsed.FSID, currentParsed.Inode)
		_, found, getErr := transaction.Get(ctx, key)
		if getErr != nil {
			return fail(getErr)
		}
		value, encodeErr := (schema.ReverseInodeRecord{LatestRevision: reconciled.Revision, State: schema.ReferenceCurrent}).MarshalBinary()
		if encodeErr != nil {
			return fail(encodeErr)
		}
		puts[string(key)] = Mutation{Key: key, Value: value}
		countKey := schema.ReferenceCountKey(id)
		count, countErr := transactionReferenceCount(ctx, transaction, puts, countKey)
		if countErr != nil {
			return fail(countErr)
		}
		occurrences := countID(reconciled.ContentIDs, id)
		if math.MaxUint64-count.TotalReferences < occurrences || count.DistinctRevisions == math.MaxUint64 || (!found && count.DistinctInodes == math.MaxUint64) {
			return fail(fmt.Errorf("reference count overflow"))
		}
		count.TotalReferences += occurrences
		count.DistinctRevisions++
		if !found {
			count.DistinctInodes++
		}
		count.UpdateSequence = reconciled.Revision
		encoded, encodeErr := count.MarshalBinary()
		if encodeErr != nil {
			return fail(encodeErr)
		}
		puts[string(countKey)] = Mutation{Key: countKey, Value: encoded}
	}

	if len(segments) > 0 {
		segmentByID := make(map[schema.ID]uint32, len(newUnique))
		for index, id := range reconciled.ContentIDs {
			if _, found := segmentByID[id]; !found {
				segmentByID[id] = uint32(index / schema.DefaultContentSegmentIDs)
			}
		}
		for id, segment := range segmentByID {
			key := schema.ReverseManifestKey(id, manifestID)
			_, found, getErr := transaction.Get(ctx, key)
			if getErr != nil {
				return fail(getErr)
			}
			value, encodeErr := (schema.ReverseManifestRecord{Segment: segment, State: schema.ReferenceCurrent}).MarshalBinary()
			if encodeErr != nil {
				return fail(encodeErr)
			}
			puts[string(key)] = Mutation{Key: key, Value: value}
			if !found {
				countKey := schema.ReferenceCountKey(id)
				count, countErr := transactionReferenceCount(ctx, transaction, puts, countKey)
				if countErr != nil {
					return fail(countErr)
				}
				if count.TotalReferences == math.MaxUint64 || count.DistinctManifests == math.MaxUint64 {
					return fail(fmt.Errorf("reference count overflow"))
				}
				count.TotalReferences++
				count.DistinctManifests++
				count.UpdateSequence = reconciled.Revision
				encoded, encodeErr := count.MarshalBinary()
				if encodeErr != nil {
					return fail(encodeErr)
				}
				puts[string(countKey)] = Mutation{Key: countKey, Value: encoded}
			}
		}
	}

	for _, key := range reconciled.DebtKeys {
		value, found, getErr := transaction.Get(ctx, key)
		if getErr != nil {
			return fail(getErr)
		}
		if !found {
			continue
		}
		debt, decodeErr := schema.UnmarshalCrawlDebtRecord(value)
		if decodeErr != nil {
			return fail(decodeErr)
		}
		debt.Status = schema.DebtResolved
		debt.ErrorClass = ""
		debt.LastAttemptUnixNano = time.Now().UnixNano()
		encoded, encodeErr := debt.MarshalBinary()
		if encodeErr != nil {
			return fail(encodeErr)
		}
		puts[string(key)] = Mutation{Key: key, Value: encoded}
	}

	// Publish hardlink reference records for multi-parent inodes.
	if reconciled.HasMultipleParents && len(reconciled.HardlinkParents) > 0 {
		hrRec := schema.HardlinkRefsRecord{
			FSID: revisionParsed.FSID, Inode: revisionParsed.Inode, Revision: reconciled.Revision,
			Parents: reconciled.HardlinkParents, Freshness: schema.FreshnessVerified,
		}
		hrEncoded, hrErr := hrRec.MarshalBinary()
		if hrErr != nil {
			return fail(hrErr)
		}
		hrKey := schema.HardlinkRefsKey(revisionParsed.FSID, revisionParsed.Inode, reconciled.Revision)
		puts[string(hrKey)] = Mutation{Key: hrKey, Value: hrEncoded}
	}

	mutations := make([]Mutation, 0, len(puts))
	for _, mutation := range puts {
		mutations = append(mutations, mutation)
	}
	sort.Slice(mutations, func(left, right int) bool { return bytes.Compare(mutations[left].Key, mutations[right].Key) < 0 })
	if err := writeTransactionBatches(ctx, transaction, store.client.Limits(), mutations, nil); err != nil {
		return fail(err)
	}
	if err := transaction.Commit(ctx); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	return nil
}

func reconciledManifest(ids []schema.ID) (schema.ID, []schema.ContentManifest, error) {
	if len(ids) <= schema.MaxInlineContentIDs {
		return schema.ID{}, nil, nil
	}
	return schema.SegmentContent(ids, schema.DefaultContentSegmentIDs)
}

func transactionContentIDs(ctx context.Context, transaction *Transaction, record schema.InodeRevision) ([]schema.ID, error) {
	switch record.ContentMode {
	case schema.ContentNone:
		return nil, nil
	case schema.ContentInline:
		return append([]schema.ID(nil), record.ContentIDs...), nil
	case schema.ContentManifestRef:
		segmentCount := (uint64(record.ContentCount) + schema.DefaultContentSegmentIDs - 1) / schema.DefaultContentSegmentIDs
		segments := make([]schema.ContentManifest, segmentCount)
		for index := range segments {
			value, found, err := transaction.Get(ctx, schema.ContentManifestKey(record.ContentManifestID, uint32(index)))
			if err != nil {
				return nil, err
			}
			if !found {
				return nil, fmt.Errorf("content manifest segment is missing")
			}
			segments[index], err = schema.UnmarshalContentManifest(value)
			if err != nil {
				return nil, err
			}
		}
		return schema.AssembleContent(record.ContentManifestID, segments)
	default:
		return nil, fmt.Errorf("invalid content mode")
	}
}

func transactionReferenceCount(ctx context.Context, transaction *Transaction, puts map[string]Mutation, key []byte) (schema.ReferenceCountRecord, error) {
	if mutation, found := puts[string(key)]; found {
		return schema.UnmarshalReferenceCountRecord(mutation.Value)
	}
	value, found, err := transaction.Get(ctx, key)
	if err != nil || !found {
		return schema.ReferenceCountRecord{}, err
	}
	return schema.UnmarshalReferenceCountRecord(value)
}

func uniqueSchemaIDs(ids []schema.ID) []schema.ID {
	seen := make(map[schema.ID]struct{}, len(ids))
	result := make([]schema.ID, 0, len(ids))
	for _, id := range ids {
		if _, found := seen[id]; found {
			continue
		}
		seen[id] = struct{}{}
		result = append(result, id)
	}
	return result
}

func countID(ids []schema.ID, target schema.ID) uint64 {
	var count uint64
	for _, id := range ids {
		if id == target {
			count++
		}
	}
	return count
}

func validateRelatedMutations(puts []Mutation, deletes [][]byte) error {
	if err := validateDistinctMutations(puts, deletes); err != nil {
		return err
	}
	for _, put := range puts {
		if err := validateMutableKey(put.Key); err != nil {
			return err
		}
		if err := schema.ValidateValue(put.Key, put.Value); err != nil {
			return err
		}
	}
	for _, key := range deletes {
		if err := validateMutableDeleteKey(key); err != nil {
			return err
		}
	}
	return nil
}

func writeTransactionBatches(ctx context.Context, transaction *Transaction, limits Limits, puts []Mutation, deletes [][]byte) error {
	if limits.MaxBatchItems == 0 || limits.MaxMessageBytes < 1024 {
		return fmt.Errorf("vaulticdb advertised insufficient transaction batch limits")
	}
	maxBytes := uint64(limits.MaxMessageBytes) - 512
	for putStart := 0; putStart < len(puts); {
		used := uint64(128)
		putEnd := putStart
		for putEnd < len(puts) && uint64(putEnd-putStart) < uint64(limits.MaxBatchItems) {
			size := uint64(len(puts[putEnd].Key)+len(puts[putEnd].Value)) + 32
			if size > maxBytes {
				return fmt.Errorf("schema mutation exceeds daemon message limit")
			}
			if used+size > maxBytes {
				break
			}
			used += size
			putEnd++
		}
		if putEnd == putStart {
			return fmt.Errorf("schema mutation batch made no progress")
		}
		if err := transaction.WriteBatch(ctx, puts[putStart:putEnd], nil); err != nil {
			return err
		}
		putStart = putEnd
	}
	for deleteStart := 0; deleteStart < len(deletes); {
		used := uint64(128)
		deleteEnd := deleteStart
		for deleteEnd < len(deletes) && uint64(deleteEnd-deleteStart) < uint64(limits.MaxBatchItems) {
			size := uint64(len(deletes[deleteEnd])) + 16
			if size > maxBytes {
				return fmt.Errorf("schema delete exceeds daemon message limit")
			}
			if used+size > maxBytes {
				break
			}
			used += size
			deleteEnd++
		}
		if deleteEnd == deleteStart {
			return fmt.Errorf("schema delete batch made no progress")
		}
		if err := transaction.WriteBatch(ctx, nil, deletes[deleteStart:deleteEnd]); err != nil {
			return err
		}
		deleteStart = deleteEnd
	}
	return nil
}

func validateDistinctMutations(puts []Mutation, deletes [][]byte) error {
	seen := make(map[string]struct{}, len(puts)+len(deletes))
	for _, put := range puts {
		key := string(put.Key)
		if _, duplicate := seen[key]; duplicate {
			return fmt.Errorf("schema batch contains duplicate key")
		}
		seen[key] = struct{}{}
	}
	for _, deleteKey := range deletes {
		key := string(deleteKey)
		if _, duplicate := seen[key]; duplicate {
			return fmt.Errorf("schema batch contains duplicate key")
		}
		seen[key] = struct{}{}
	}
	return nil
}

// AllocateRevision atomically returns one durable, monotonically increasing
// repository revision sequence. Serializable conflicts are retried.
func (store *SchemaStore) AllocateRevision(ctx context.Context) (uint64, error) {
	key := schema.NextRevisionKey()
	backoff := 100 * time.Microsecond
	for range revisionAllocationAttempts {
		transaction, err := store.client.Begin(ctx)
		if err != nil {
			return 0, err
		}
		encoded, found, err := transaction.Get(ctx, key)
		if err != nil {
			rollbackTransaction(ctx, transaction)
			return 0, err
		}
		next := uint64(1)
		if found {
			next, err = schema.UnmarshalNextRevision(encoded)
			if err != nil {
				rollbackTransaction(ctx, transaction)
				return 0, err
			}
		}
		if next == math.MaxUint64 {
			rollbackTransaction(ctx, transaction)
			return 0, fmt.Errorf("repository revision sequence exhausted")
		}
		encodedNext, err := schema.MarshalNextRevision(next + 1)
		if err != nil {
			rollbackTransaction(ctx, transaction)
			return 0, err
		}
		if err := transaction.WriteBatch(ctx, []Mutation{{Key: key, Value: encodedNext}}, nil); err != nil {
			rollbackTransaction(ctx, transaction)
			return 0, err
		}
		if err := transaction.Commit(ctx); err != nil {
			rollbackTransaction(ctx, transaction)
			if status.Code(err) == codes.Aborted {
				timer := time.NewTimer(backoff)
				select {
				case <-ctx.Done():
					timer.Stop()
					return 0, ctx.Err()
				case <-timer.C:
				}
				backoff = min(backoff*2, 25*time.Millisecond)
				continue
			}
			return 0, err
		}
		return next, nil
	}
	return 0, fmt.Errorf("allocate repository revision: %w", errors.New("transaction conflict retry limit exceeded"))
}

func rollbackTransaction(ctx context.Context, transaction *Transaction) error {
	cleanupCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), defaultRPCDeadline)
	defer cancel()
	return transaction.Rollback(cleanupCtx)
}
