package daemon

import (
	"context"
	"errors"
	"fmt"
	"math"
	"sync"
	"time"

	"github.com/otuschhoff/vaultic/internal/index/schema"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

const revisionAllocationAttempts = 128

const freshImportSeenBytes = 64 << 20

// SchemaStore applies the Vaultic schema's immutability and revision rules over
// the bounded daemon client.
type SchemaStore struct {
	client           *Client
	publicationMu    sync.RWMutex
	legacyImportGate chan struct{}
	freshImportSeen  *idSeenFilter
}

type idSeenFilter struct {
	bits []byte
}

func newIDSeenFilter(size int) *idSeenFilter {
	return &idSeenFilter{bits: make([]byte, size)}
}

func (filter *idSeenFilter) possiblyContains(id schema.ID) bool {
	for offset := 0; offset < len(id); offset += 8 {
		value := uint64(id[offset])<<56 | uint64(id[offset+1])<<48 | uint64(id[offset+2])<<40 |
			uint64(id[offset+3])<<32 | uint64(id[offset+4])<<24 | uint64(id[offset+5])<<16 |
			uint64(id[offset+6])<<8 | uint64(id[offset+7])
		bit := value % uint64(len(filter.bits)*8)
		if filter.bits[bit/8]&(1<<uint(bit%8)) == 0 {
			return false
		}
	}
	return true
}

func (filter *idSeenFilter) insert(id schema.ID) {
	for offset := 0; offset < len(id); offset += 8 {
		value := uint64(id[offset])<<56 | uint64(id[offset+1])<<48 | uint64(id[offset+2])<<40 |
			uint64(id[offset+3])<<32 | uint64(id[offset+4])<<24 | uint64(id[offset+5])<<16 |
			uint64(id[offset+6])<<8 | uint64(id[offset+7])
		bit := value % uint64(len(filter.bits)*8)
		filter.bits[bit/8] |= 1 << uint(bit%8)
	}
}

func (s *SchemaStore) freshImportLookupHints(imported LegacyPackImport) legacyImportHints {
	hints := legacyImportHints{}
	if s.freshImportSeen == nil {
		return hints
	}
	hints.packAbsent = !s.freshImportSeen.possiblyContains(imported.PackID)
	hints.blobsAbsent = make(map[schema.ID]struct{}, len(imported.Blobs))
	for blobID := range imported.Blobs {
		if !s.freshImportSeen.possiblyContains(blobID) {
			hints.blobsAbsent[blobID] = struct{}{}
		}
	}
	return hints
}

// EnableFreshLegacyImport skips reads only for IDs not previously committed by
// this store. It is safe only for a candidate reset to empty immediately before import.
func (s *SchemaStore) EnableFreshLegacyImport() {
	s.freshImportSeen = newIDSeenFilter(freshImportSeenBytes)
}

type legacyImportHints struct {
	packAbsent  bool
	blobsAbsent map[schema.ID]struct{}
}

// CheckEncryption validates the underlying metadata objects without exposing keys.
func (s *SchemaStore) CheckEncryption(ctx context.Context) (EncryptionAudit, error) {
	return s.client.CheckEncryption(ctx)
}

type LegacyPackImport struct {
	SourceIndex schema.ID
	PackID      schema.ID
	Record      schema.PackRecord
	Blobs       map[schema.ID]schema.BlobRecord
	Placements  map[uint64]schema.PlacementRecord
	BatchSize   uint32
	DebtKey     []byte
	Debt        *schema.CrawlDebtRecord
	// RunID groups the history events emitted by one operator-visible run.
	RunID schema.ID
	// PredecessorPackIDs records repack lineage when this pack replaces others.
	PredecessorPackIDs []schema.ID
	LineageKind        schema.RepackLineageKind
}

// PublishedPack contains the catalog and blob locations generated by a new
// backup pack. Unlike legacy imports it has no source JSON index.
type PublishedPack struct {
	PackID schema.ID
	Record schema.PackRecord
	Blobs  map[schema.ID]schema.BlobRecord
	// Placements records where the pack bytes physically live, keyed by backend
	// hash. These are written atomically with the pack transition that produced
	// them.
	Placements map[uint64]schema.PlacementRecord
	// PredecessorPackIDs carries repack lineage when this pack replaces others,
	// so a reader can tell a rewrite from genuine new data.
	PredecessorPackIDs []schema.ID
	LineageKind        schema.RepackLineageKind
	RunID              schema.ID
}

type SnapshotScope struct {
	SnapshotID   schema.ID
	RootKey      []byte
	OriginalJSON []byte
	Crawl        *AuthoritativeCrawlClaim
}

type AuthoritativeCrawlClaim struct {
	ScopeID    schema.ID
	RootFSID   uint32
	RootInode  uint64
	StartFence uint64
	Complete   bool
	DebtKeys   [][]byte
}

type ReconciledRevision struct {
	CurrentKey         []byte
	RevisionKey        []byte
	RevisionValue      []byte
	Revision           uint64
	ContentIDs         []schema.ID
	DebtKeys           [][]byte
	RelatedPuts        []Mutation
	HasMultipleParents bool
	HardlinkParents    []schema.HardlinkParentRef
}

func NewSchemaStore(client *Client) *SchemaStore {
	return &SchemaStore{client: client, legacyImportGate: make(chan struct{}, 1)}
}

func (store *SchemaStore) LockAnalyticsPublication() {
	store.publicationMu.Lock()
}

func (store *SchemaStore) UnlockAnalyticsPublication() {
	store.publicationMu.Unlock()
}

func (store *SchemaStore) RLockAnalyticsPublication() {
	store.publicationMu.RLock()
}

func (store *SchemaStore) RUnlockAnalyticsPublication() {
	store.publicationMu.RUnlock()
}

func (store *SchemaStore) Get(ctx context.Context, key []byte) ([]byte, bool, error) {
	if _, err := schema.ParseKey(key); err != nil {
		return nil, false, err
	}
	return store.client.Get(ctx, key, "")
}

// MultiGet reads a bounded set of schema records in request order.
func (store *SchemaStore) MultiGet(ctx context.Context, keys [][]byte) ([]KeyValue, []bool, error) {
	for _, key := range keys {
		if _, err := schema.ParseKey(key); err != nil {
			return nil, nil, err
		}
	}
	return store.client.MultiGet(ctx, keys, "")
}

// ScanPrefix reads one bounded schema page for an exact key prefix.
func (store *SchemaStore) ScanPrefix(ctx context.Context, prefix, afterKey []byte, pageSize uint32) ([]KeyValue, bool, error) {
	if pageSize > store.client.Limits().MaxPageItems {
		pageSize = store.client.Limits().MaxPageItems
	}
	return store.client.ScanPage(ctx, prefix, afterKey, pageSize, "")
}

// MetadataHead returns the highest globally allocated authoritative commit.
func (store *SchemaStore) MetadataHead(ctx context.Context) (uint64, error) {
	value, found, err := store.Get(ctx, schema.NextRevisionKey())
	if err != nil || !found {
		return 0, err
	}
	next, err := schema.UnmarshalNextRevision(value)
	if err != nil {
		return 0, err
	}
	if next == 0 {
		return 0, fmt.Errorf("invalid next metadata revision")
	}
	return next - 1, nil
}

// RecordCrawlDebtFailure leaves debt pending while atomically recording a
// failed reconciliation attempt for each existing debt key.
func (store *SchemaStore) RecordCrawlDebtFailure(ctx context.Context, keys [][]byte, errorClass string) error {
	if errorClass == "" {
		errorClass = "reconciliation-failed"
	}
	backoff := 100 * time.Microsecond
	for range revisionAllocationAttempts {
		err := store.recordCrawlDebtFailureOnce(ctx, keys, errorClass)
		if status.Code(err) != codes.Aborted {
			return err
		}
		timer := time.NewTimer(backoff)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
		}
		backoff = min(backoff*2, 25*time.Millisecond)
	}
	return fmt.Errorf("record crawl-debt failure: transaction conflict retry limit exceeded")
}

// ResolveCrawlDebt atomically marks existing debt records resolved without
// creating an otherwise identical metadata revision.
func (store *SchemaStore) ResolveCrawlDebt(ctx context.Context, keys [][]byte) error {
	backoff := 100 * time.Microsecond
	for range revisionAllocationAttempts {
		err := store.resolveCrawlDebtOnce(ctx, keys)
		if status.Code(err) != codes.Aborted {
			return err
		}
		timer := time.NewTimer(backoff)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
		}
		backoff = min(backoff*2, 25*time.Millisecond)
	}
	return fmt.Errorf("resolve crawl debt: transaction conflict retry limit exceeded")
}

func (store *SchemaStore) resolveCrawlDebtOnce(ctx context.Context, keys [][]byte) error {
	transaction, err := store.client.Begin(ctx)
	if err != nil {
		return err
	}
	puts := make([]Mutation, 0, len(keys))
	for _, key := range keys {
		parsed, parseErr := schema.ParseKey(key)
		if parseErr != nil || parsed.Kind != schema.KeyCrawlDebt {
			rollbackTransaction(ctx, transaction)
			return fmt.Errorf("invalid crawl-debt key")
		}
		value, found, getErr := transaction.Get(ctx, key)
		if getErr != nil {
			rollbackTransaction(ctx, transaction)
			return getErr
		}
		if !found {
			continue
		}
		debt, decodeErr := schema.UnmarshalCrawlDebtRecord(value)
		if decodeErr != nil {
			rollbackTransaction(ctx, transaction)
			return decodeErr
		}
		if debt.Status == schema.DebtResolved {
			continue
		}
		debt.Status = schema.DebtResolved
		debt.ErrorClass = ""
		debt.LastAttemptUnixNano = time.Now().UnixNano()
		encoded, encodeErr := debt.MarshalBinary()
		if encodeErr != nil {
			rollbackTransaction(ctx, transaction)
			return encodeErr
		}
		puts = append(puts, Mutation{Key: key, Value: encoded})
	}
	if err := writeTransactionBatches(ctx, transaction, store.client.Limits(), puts, nil); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	if err := transaction.Commit(ctx); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	return nil
}

func (store *SchemaStore) recordCrawlDebtFailureOnce(ctx context.Context, keys [][]byte, errorClass string) error {
	transaction, err := store.client.Begin(ctx)
	if err != nil {
		return err
	}
	puts := make([]Mutation, 0, len(keys))
	for _, key := range keys {
		parsed, parseErr := schema.ParseKey(key)
		if parseErr != nil || parsed.Kind != schema.KeyCrawlDebt {
			rollbackTransaction(ctx, transaction)
			return fmt.Errorf("invalid crawl-debt key")
		}
		value, found, getErr := transaction.Get(ctx, key)
		if getErr != nil {
			rollbackTransaction(ctx, transaction)
			return getErr
		}
		if !found {
			continue
		}
		debt, decodeErr := schema.UnmarshalCrawlDebtRecord(value)
		if decodeErr != nil {
			rollbackTransaction(ctx, transaction)
			return decodeErr
		}
		if debt.Status == schema.DebtResolved {
			continue
		}
		if debt.RetryCount < math.MaxUint32 {
			debt.RetryCount++
		}
		debt.Status = schema.DebtPending
		debt.LastAttemptUnixNano = time.Now().UnixNano()
		debt.ErrorClass = errorClass
		encoded, encodeErr := debt.MarshalBinary()
		if encodeErr != nil {
			rollbackTransaction(ctx, transaction)
			return encodeErr
		}
		puts = append(puts, Mutation{Key: key, Value: encoded})
	}
	if err := writeTransactionBatches(ctx, transaction, store.client.Limits(), puts, nil); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	if err := transaction.Commit(ctx); err != nil {
		rollbackTransaction(ctx, transaction)
		return err
	}
	return nil
}

// ImportLegacyPack atomically merges one legacy pack's blob locations,
// provenance, catalog record, aggregates, and optional pack-stat debt.
func (store *SchemaStore) ImportLegacyPack(ctx context.Context, imported LegacyPackImport) error {
	select {
	case store.legacyImportGate <- struct{}{}:
		defer func() { <-store.legacyImportGate }()
	case <-ctx.Done():
		return ctx.Err()
	}
	hints := store.freshImportLookupHints(imported)
	deferDurability := store.freshImportSeen != nil

	backoff := 100 * time.Microsecond
	for range revisionAllocationAttempts {
		err := store.importPackOnce(ctx, imported, true, hints, deferDurability)
		if status.Code(err) != codes.Aborted {
			if err == nil && store.freshImportSeen != nil {
				store.freshImportSeen.insert(imported.PackID)
				for blobID := range imported.Blobs {
					store.freshImportSeen.insert(blobID)
				}
			}
			return err
		}
		timer := time.NewTimer(backoff)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
		}
		backoff = min(backoff*2, 25*time.Millisecond)
	}
	return fmt.Errorf("import legacy pack: %w", errors.New("transaction conflict retry limit exceeded"))
}
