// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.0
// source: vaulticd/v1/daemon.proto

package vaulticdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_vaulticd_v1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticd_v1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_vaulticd_v1_daemon_proto_rawDescGZIP(), []int{0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepositoryId  string                 `protobuf:"bytes,1,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_vaulticd_v1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticd_v1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_vaulticd_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *HealthRequest) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DaemonId        string                 `protobuf:"bytes,1,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SchemaVersion   string                 `protobuf:"bytes,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RepositoryId    string                 `protobuf:"bytes,4,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	SlateDbRevision string                 `protobuf:"bytes,5,opt,name=slate_db_revision,json=slateDbRevision,proto3" json:"slate_db_revision,omitempty"`
	Ready           bool                   `protobuf:"varint,6,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_vaulticd_v1_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticd_v1_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_vaulticd_v1_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *HealthResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HealthResponse) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *HealthResponse) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

func (x *HealthResponse) GetSlateDbRevision() string {
	if x != nil {
		return x.SlateDbRevision
	}
	return ""
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepositoryId  string                 `protobuf:"bytes,1,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_vaulticd_v1_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticd_v1_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_vaulticd_v1_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *CapabilitiesRequest) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

type CapabilitiesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DaemonId        string                 `protobuf:"bytes,1,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SchemaVersion   string                 `protobuf:"bytes,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RepositoryId    string                 `protobuf:"bytes,4,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	UnixSocket      bool                   `protobuf:"varint,5,opt,name=unix_socket,json=unixSocket,proto3" json:"unix_socket,omitempty"`
	TcpEnabled      bool                   `protobuf:"varint,6,opt,name=tcp_enabled,json=tcpEnabled,proto3" json:"tcp_enabled,omitempty"`
	MaxBatchItems   uint32                 `protobuf:"varint,7,opt,name=max_batch_items,json=maxBatchItems,proto3" json:"max_batch_items,omitempty"`
	MaxMessageBytes uint32                 `protobuf:"varint,8,opt,name=max_message_bytes,json=maxMessageBytes,proto3" json:"max_message_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_vaulticd_v1_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaulticd_v1_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_vaulticd_v1_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *CapabilitiesResponse) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *CapabilitiesResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *CapabilitiesResponse) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

func (x *CapabilitiesResponse) GetUnixSocket() bool {
	if x != nil {
		return x.UnixSocket
	}
	return false
}

func (x *CapabilitiesResponse) GetTcpEnabled() bool {
	if x != nil {
		return x.TcpEnabled
	}
	return false
}

func (x *CapabilitiesResponse) GetMaxBatchItems() uint32 {
	if x != nil {
		return x.MaxBatchItems
	}
	return 0
}

func (x *CapabilitiesResponse) GetMaxMessageBytes() uint32 {
	if x != nil {
		return x.MaxMessageBytes
	}
	return 0
}

var File_vaulticd_v1_daemon_proto protoreflect.FileDescriptor

const file_vaulticd_v1_daemon_proto_rawDesc = "" +
	"\n" +
	"\x18vaulticd/v1/daemon.proto\x12\vvaulticd.v1\"\a\n" +
	"\x05Empty\"4\n" +
	"\rHealthRequest\x12#\n" +
	"\rrepository_id\x18\x01 \x01(\tR\frepositoryId\"\xe6\x01\n" +
	"\x0eHealthResponse\x12\x1b\n" +
	"\tdaemon_id\x18\x01 \x01(\tR\bdaemonId\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\tR\rschemaVersion\x12#\n" +
	"\rrepository_id\x18\x04 \x01(\tR\frepositoryId\x12*\n" +
	"\x11slate_db_revision\x18\x05 \x01(\tR\x0fslateDbRevision\x12\x14\n" +
	"\x05ready\x18\x06 \x01(\bR\x05ready\":\n" +
	"\x13CapabilitiesRequest\x12#\n" +
	"\rrepository_id\x18\x01 \x01(\tR\frepositoryId\"\xc0\x02\n" +
	"\x14CapabilitiesResponse\x12\x1b\n" +
	"\tdaemon_id\x18\x01 \x01(\tR\bdaemonId\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\tR\rschemaVersion\x12#\n" +
	"\rrepository_id\x18\x04 \x01(\tR\frepositoryId\x12\x1f\n" +
	"\vunix_socket\x18\x05 \x01(\bR\n" +
	"unixSocket\x12\x1f\n" +
	"\vtcp_enabled\x18\x06 \x01(\bR\n" +
	"tcpEnabled\x12&\n" +
	"\x0fmax_batch_items\x18\a \x01(\rR\rmaxBatchItems\x12*\n" +
	"\x11max_message_bytes\x18\b \x01(\rR\x0fmaxMessageBytes2\x8c\x02\n" +
	"\rVaulticDaemon\x12A\n" +
	"\x06Health\x12\x1a.vaulticd.v1.HealthRequest\x1a\x1b.vaulticd.v1.HealthResponse\x12S\n" +
	"\fCapabilities\x12 .vaulticd.v1.CapabilitiesRequest\x1a!.vaulticd.v1.CapabilitiesResponse\x12/\n" +
	"\x05Drain\x12\x12.vaulticd.v1.Empty\x1a\x12.vaulticd.v1.Empty\x122\n" +
	"\bShutdown\x12\x12.vaulticd.v1.Empty\x1a\x12.vaulticd.v1.EmptyBJZHgithub.com/otuschhoff/vaultic/internal/index/proto/vaulticdv1;vaulticdv1b\x06proto3"

var (
	file_vaulticd_v1_daemon_proto_rawDescOnce sync.Once
	file_vaulticd_v1_daemon_proto_rawDescData []byte
)

func file_vaulticd_v1_daemon_proto_rawDescGZIP() []byte {
	file_vaulticd_v1_daemon_proto_rawDescOnce.Do(func() {
		file_vaulticd_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vaulticd_v1_daemon_proto_rawDesc), len(file_vaulticd_v1_daemon_proto_rawDesc)))
	})
	return file_vaulticd_v1_daemon_proto_rawDescData
}

var file_vaulticd_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_vaulticd_v1_daemon_proto_goTypes = []any{
	(*Empty)(nil),                // 0: vaulticd.v1.Empty
	(*HealthRequest)(nil),        // 1: vaulticd.v1.HealthRequest
	(*HealthResponse)(nil),       // 2: vaulticd.v1.HealthResponse
	(*CapabilitiesRequest)(nil),  // 3: vaulticd.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 4: vaulticd.v1.CapabilitiesResponse
}
var file_vaulticd_v1_daemon_proto_depIdxs = []int32{
	1, // 0: vaulticd.v1.VaulticDaemon.Health:input_type -> vaulticd.v1.HealthRequest
	3, // 1: vaulticd.v1.VaulticDaemon.Capabilities:input_type -> vaulticd.v1.CapabilitiesRequest
	0, // 2: vaulticd.v1.VaulticDaemon.Drain:input_type -> vaulticd.v1.Empty
	0, // 3: vaulticd.v1.VaulticDaemon.Shutdown:input_type -> vaulticd.v1.Empty
	2, // 4: vaulticd.v1.VaulticDaemon.Health:output_type -> vaulticd.v1.HealthResponse
	4, // 5: vaulticd.v1.VaulticDaemon.Capabilities:output_type -> vaulticd.v1.CapabilitiesResponse
	0, // 6: vaulticd.v1.VaulticDaemon.Drain:output_type -> vaulticd.v1.Empty
	0, // 7: vaulticd.v1.VaulticDaemon.Shutdown:output_type -> vaulticd.v1.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vaulticd_v1_daemon_proto_init() }
func file_vaulticd_v1_daemon_proto_init() {
	if File_vaulticd_v1_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vaulticd_v1_daemon_proto_rawDesc), len(file_vaulticd_v1_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vaulticd_v1_daemon_proto_goTypes,
		DependencyIndexes: file_vaulticd_v1_daemon_proto_depIdxs,
		MessageInfos:      file_vaulticd_v1_daemon_proto_msgTypes,
	}.Build()
	File_vaulticd_v1_daemon_proto = out.File
	file_vaulticd_v1_daemon_proto_goTypes = nil
	file_vaulticd_v1_daemon_proto_depIdxs = nil
}
