// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: vaulticd/v1/daemon.proto

package vaulticdv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VaulticDaemon_Health_FullMethodName       = "/vaulticd.v1.VaulticDaemon/Health"
	VaulticDaemon_Capabilities_FullMethodName = "/vaulticd.v1.VaulticDaemon/Capabilities"
	VaulticDaemon_Drain_FullMethodName        = "/vaulticd.v1.VaulticDaemon/Drain"
	VaulticDaemon_Shutdown_FullMethodName     = "/vaulticd.v1.VaulticDaemon/Shutdown"
)

// VaulticDaemonClient is the client API for VaulticDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VaulticDaemonClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	Drain(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type vaulticDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewVaulticDaemonClient(cc grpc.ClientConnInterface) VaulticDaemonClient {
	return &vaulticDaemonClient{cc}
}

func (c *vaulticDaemonClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, VaulticDaemon_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDaemonClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, VaulticDaemon_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDaemonClient) Drain(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VaulticDaemon_Drain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaulticDaemonClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VaulticDaemon_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VaulticDaemonServer is the server API for VaulticDaemon service.
// All implementations must embed UnimplementedVaulticDaemonServer
// for forward compatibility.
type VaulticDaemonServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	Drain(context.Context, *Empty) (*Empty, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedVaulticDaemonServer()
}

// UnimplementedVaulticDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVaulticDaemonServer struct{}

func (UnimplementedVaulticDaemonServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedVaulticDaemonServer) Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedVaulticDaemonServer) Drain(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Drain not implemented")
}
func (UnimplementedVaulticDaemonServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedVaulticDaemonServer) mustEmbedUnimplementedVaulticDaemonServer() {}
func (UnimplementedVaulticDaemonServer) testEmbeddedByValue()                       {}

// UnsafeVaulticDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VaulticDaemonServer will
// result in compilation errors.
type UnsafeVaulticDaemonServer interface {
	mustEmbedUnimplementedVaulticDaemonServer()
}

func RegisterVaulticDaemonServer(s grpc.ServiceRegistrar, srv VaulticDaemonServer) {
	// If the following call pancis, it indicates UnimplementedVaulticDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VaulticDaemon_ServiceDesc, srv)
}

func _VaulticDaemon_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDaemonServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDaemon_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDaemonServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDaemon_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDaemonServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDaemon_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDaemonServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDaemon_Drain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDaemonServer).Drain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDaemon_Drain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDaemonServer).Drain(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaulticDaemon_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaulticDaemonServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaulticDaemon_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaulticDaemonServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// VaulticDaemon_ServiceDesc is the grpc.ServiceDesc for VaulticDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VaulticDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vaulticd.v1.VaulticDaemon",
	HandlerType: (*VaulticDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _VaulticDaemon_Health_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _VaulticDaemon_Capabilities_Handler,
		},
		{
			MethodName: "Drain",
			Handler:    _VaulticDaemon_Drain_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _VaulticDaemon_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vaulticd/v1/daemon.proto",
}
