FROM golang:1.26-bookworm AS go-toolchain

FROM rust:1-bookworm AS rust-toolchain

FROM rust-toolchain AS rados-rust-toolchain

WORKDIR /src
RUN apt-get update && apt-get install --yes --no-install-recommends \
        cmake \
        binutils \
        gcc \
        g++ \
        git \
        libudev-dev \
        make \
        pkg-config \
        protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*
